---
title: "Weapon Systems of The Twenty First Century"
subtitle: "The Upside-down Revolution"
author: "Stanisław Lem"
date: "1983-10"
categories: [war, scifi, fun]
format:
  html:
    toc: true
description: "Stanisław Lem's review of a fictitious book that predicts 21th century drone warfare."

status: "finished"
confidence: "log"
importance: 3
---

{{< include ../../../static/_macros.tex >}}

## I

Having gained access (by what means, I'm not at liberty to reveal) to several volumes on the military history of the twenty-first century, I pondered, first and foremost, how to hide the information they contained. The question of concealment was most important, because I understood that the man who knew this history was like the finder of a treasure who, defenseless, could easily lose it along with his life. I alone possessed these facts, I realized, thanks to the books that Dr. R.G. loaned to me briefly and which I returned just before his premature death. As far as I know, he burned them, thus taking the secret with him to the grave. Silence seemed the simplest solution: if I kept quiet, I would save my skin. But what a shame, to sit on a thousand and one extraordinary things having to do with the political history of the next century, things opening up completely new horizons in all areas of human life. Take, for example, the astonishing reversal -- completely unforeseen -- in the field of artificial intelligence (AI), which became a force to be reckoned with precisely because it did not become the machine embodiment of the human mind. If I remained silent for my own safety, I would be depriving myself of all the advantages stemming from that knowledge.

Another idea occurred to me: to write down exactly what I remembered of those volumes and place the manuscript in a bank vault. It would be necessary to write down everything I retained from my reading, because with the passage of time I would forget many particulars of such a broad subject. Then, if I wanted to refresh my memory, I could visit the vault, take notes there, and return the manuscript to the strongbox. But it was dangerous. Someone could spy on me. Besides, in today's world no bank vault was 100-percent secure. Even a thief of low intelligence would figure out, sooner or later, what an extraordinary document had fallen into his hands. And even if he discarded and destroyed my manuscript, I would not know it and would live in constant dread that the connection between my person and the history of the twenty-first century would come to light.

My dilemma was how to hide the secret forever but at the same time take advantage of it freely -- to hide it from the world but not from myself. After much deliberation, I realized that this could be done very easily. The safest way to conceal a remarkable idea -- every word of it true -- was to publish it as science fiction. Just as a diamond thrown on a heap of broken glass would become invisible, so an authentic revelation placed amid the stupidities of science fiction would take on their coloration -- and cease to be dangerous.

At first, however, still fearful, I made a very modest use of the secret I possessed. In 1967 I wrote a science-fiction novel entitled *His Master's Voice* (published in English in 1983 by Harcourt Brace Jovanovich). On page 125 of that edition, third line from the top, are the words

> "the ruling doctrine was... 'indirect economic attrition'", and then the doctrine is expressed by the aphorism "The thin starve before the fat lose weight.".

The doctrine expressed publicly in the United States in 1980 -- thirteen years after the original edition of *His Master's Voice* -- was put a little differently. (In the West German press they used the slogan "den Gegner totrüsten" -- "arm the enemy to death".)

Once I had confirmed -- and there had been time enough to do so, after all, since the book's appearance -- that no one had noticed how my "fantasizing" agreed with later political developments, I grew bolder. I understood that truth, when set in fiction, is camouflaged perfectly, and that even this fact can be safely confessed. For that matter, no one takes anything seriously if it's published. So the best way to keep a top secret secret is to put it out in a mass edition.

Having ensured the safety of my secret thus, I can now serenely set about giving a complete report. I will confine myself to the first two volumes of *Weapons Systems of the Twenty-first Century: The Upside-down Evolution*, published in 2105. I could even name the authors (none of whom has been born yet), but what would be the point? The work is in three volumes. The first presents the development of weapons from the year 1944; the second explains how the nuclear-arms race gave rise to the "unhumanizing" of warfare by transferring the production of weapons from the defense industry to the battlefield itself; and the third deals with the effect this greatest military revolution had on the subsequent history of the world. 

## II

Soon after the destruction of Hiroshima and Nagasaki, American nuclear researchers founded the Bulletin of the Atomic Scientists. On its cover they put the picture of a clock with the minute hand at ten to midnight. Six years later, after the first successful tests of the hydrogen bomb, they moved the hand five minutes closer, and when the Soviet Union acquired thermonuclear weapons the hand was moved three minutes closer. The next move would mean the end of civilization. The Bulletin's doctrine was "One World or None": the world would either unite and be saved, or would perish.

With the nuclear build-up on both sides of the ocean and the placing of ever larger payloads of plutonium and tritium in ever more accurate ballistic missiles, none of the scientists who were the "fathers of the bomb" believed that peace -- troubled as it was by local,conventional wars -- would last to the end of the century. Atomic weapons had amended Clausewitz's famous definition ("War is... a continuation of political activity by other means"),because now the threat of attack could substitute for the attack itself. Thus came about the doctrine of symmetrical deterrence known later as the "balance of terror." Different American administrations advocated it with different initials. There was, for example, MAD (MutualAssured Destruction), based on the "second-strike" principle (the ability of the country attacked to retaliate in force). The vocabulary of destruction was enriched in the next decades. There was "Total Strategic Exchange", meaning all-out nuclear war; MIRV (Multiple Independently Targetable Re-entry Vehicle), a missile firing a number of warheads simultaneously, each aimed at a different target; PENAID (Penetration Aids), dummy missiles to fool the opponent's radar; and MARY (Maneuverable Re-entry), a missile capable of evading antimissiles and of hitting the target within fifty feet of the programmed "ground zero". But to list even a hundredth of the succession of specialized terms is impossible here.

Although the danger of atomic warfare increased whenever "equality" was lessened, and therefore the rational thing would seem to have been to preserve that equality under multinational supervision, the antagonists did not reach an agreement despite repeated negotiations.

There were many reasons, which the authors of *Weapons Systems* divide into two groups.In the first group they see the pressure of traditional thinking in international politics. Tradition has determined that one should call for peace but prepare for war, upsetting the existing balance until the upper hand is gained. The second group of reasons are factors independent of human thought both political and nonpolitical; these have to do with the evolution of the major applied military technologies.

Each new possibility of technological improvement in weaponry became a reality, on the principle "If we don't do it, they will.". Meanwhile, the doctrine of nuclear warfare went through changes. At one time it advocated a limited exchange of nuclear strikes (though no one knew exactly what the guarantee of the limitation would be); at another, its goal was the total annihilation of the enemy (all of whose population became "hostages" of a sort); at still another, it gave first priority to destroying the enemy's military-industrial potential.

The ancient law of "sword and shield" still held sway in the evolution of weaponry. The shield took the form of hardening the silos that housed the missiles, while the sword to pierce the shield involved making the missiles increasingly accurate and, later, providing them with self-guidance systems and self-maneuverability. For atomic submarines the shield was the ocean; improved methods for their underwater detection constituted the sword.

Technological progress in defense sent electronic "eyes" into orbit, creating a high frontier of global reconnaissance able to spot missiles at the moment of launch. This was the  shield that the new type of sword -- the "killer satellite" -- was to break, with a laser to blind the defending "eyes," or with a lightning-like discharge of immense power to destroy the missiles themselves during their flight above the atmosphere.

But the hundreds of billions of dollars invested in building these higher and higher levels of conflict failed, ultimately, to produce any definite, and therefore valuable, strategic advantage -- and for two very different, almost unrelated reasons.

In the first place, all these improvements and innovations, instead of increasing strategic security, offensive or defensive, only reduced it. Security was reduced because the global system of each superpower grew more and more complex, composed of an increasing number of different subsystems on land, sea, and air and in space. Military success required infallible communications to guarantee the optimum synchronization of operations. But all systems that are highly complex, whether they be industrial or military, biological or technological, whether they process information or raw material, are prone to breakdown, to a degree mathematically proportional to the number of elements that make up the system. Progress in military technology carried with it a unique paradox: the more sophisticated the weapon it produced, the greater was the role of chance (which could not be calculated) in the weapon's successful use.

This fundamental problem must be explained carefully, because scientists were for a long time unable to base any technological activity on the randomness of complex systems. To counteract malfunctions in such systems, engineers introduced redundancy: power reserves, for example, or -- as with the first American space shuttles (like the [Columbia](https://en.wikipedia.org/wiki/Space_Shuttle_Columbia)) -- the doubling, even quadrupling of parallel, onboard computers. Total reliability is unattainable: if a system has a million elements and each element will malfunction only one time out of a million, a breakdown is certain.

The bodies of animals and plants consist of trillions of functioning parts, yet life copes with the phenomenon of inevitable failure. In what way? The experts call it the construction of reliable systems out of unreliable components. Natural evolution uses various tactics to counteract the fallibility of organisms: the capacity for self-repair or regeneration; surplus organs (this is why we have two kidneys instead of one, why a half-destroyed liver can still function as the body's central chemical-processing plant, and why the circulatory system has so many alternate veins and arteries); and the separation of control centers for the somatic and psychic processes. This last phenomenon gave brain researchers much trouble: they could not understand why a seriously injured brain still functioned but a slightly damaged computer refused to obey its programs.

Merely doubling control centers and parts used in twentieth-century engineering led to the absurd in actual construction. If an automated spaceship going to a distant planet were built according to the directive of multiplying pilot computers, as in the shuttles, then it would have to contain -- in view of the duration of the flight -- not four or five but possibly fifty such computers. They would operate not by "linear logic" but by "voting": once the individual computers ceased functioning identically and thus diverged in their results, one would have to accept, as the right result, what was reached by the majority. But this kind of engineering parliamentarianism led to the production of giants burdened with the woes typical of democracies: contradictory views, plans, and actions. To such pluralism, to such programmed elasticity, there had to be a limit.

We should have begun much earlier -- said the twenty-first-century specialists -- to learn from biological evolution, whose several-billion-year existence demonstrates optimal strategic engineering. A living organism is not guided by "totalitarian centralism" or "democratic pluralism", but by a strategy much more complex. Simplifying, we might call it a compromise  between concentration and separation of the regulating centers.

Meanwhile, in the late-twentieth-century phase of the arms race, the role of unpredictable chance increased. When hours (or days) and miles (or hundreds of miles) separate defeat from victory, and therefore an error of command can be remedied by throwing in reserves, or retreating, or counterattacking, then there is room to reduce the element of chance. But when micromillimeters and nanoseconds determine the outcome, then chance enters like a god of war, deciding victory or defeat; it is magnified and lifted out of the microscopic scale of atomic physics. The fastest, best weapons system comes up against the Heisenberg uncertainty principle, which nothing can overcome, because that principle is a basic property of matter in the Universe.

It need not be a computer breakdown in satellite reconnaissance or in missiles whose warheads parry defenses with laser beams; if a series of electronic defensive impulses is even a billionth of a second slow in meeting a similar series of offensive impulses, that is enough for a toss of the dice to decide the outcome of the Final Encounter.

Unaware of this state of affairs, the major antagonists of the planet devised two opposite strategies. One can call them the "scalpel" and the "hammer". The constant escalation of pay-load megatonnage was the hammer; the improvement of detection and swift destruction in flight was the scalpel. They also reckoned on the deterrent of the "dead man's revenge": the enemy would realize that even in winning he would perish, since a totally obliterated country would still respond -- automatically and posthumously -- with a strike that would make defeat universal. Such was the direction the arms race was taking, and such was its destination, which no one wanted but no one knew how to avoid.

How does the engineer minimize error in a very large, very complex system? He does trial runs to test it; he looks for weak spots, weak links. But there was no way of testing a system designed to wage global nuclear war, a system made up of surface, submarine, air-launched, and satellite missiles, antimissiles, and multiple centers of command and communications, ready to loose gigantic destructive forces in wave on wave of reciprocal atomic strikes. No maneuvers, no computer simulation, could re-create the actual conditions of such a battle.

Increasing speed of operation marked each new weapons system, particularly the decision-making function (to strike or not to strike, where, how, with what force held in reserve, at what risk, etc.), and this increasing speed also brought the incalculable factor of chance into play. Lightning-fast systems made lightning-fast mistakes. When a fraction of a second determined the safety or destruction of a region, a great metropolis, an industrial complex, or a large fleet, it was impossible to achieve military certainty. One could even say that victory had ceased to be distinguishable from defeat. In a word, the arms race was heading toward a Pyrrhic situation.

On the battlefields of yore, when knights in armor fought on horseback and foot soldiers met at close quarters, chance decided the life or death of individuals and military units. But the power of electronics, embodied in computer logic, made chance the arbiter of the fate of whole armies and nations.

Moreover -- and this was quite a separate thing -- blueprints for new, better weapons were developed so quickly that industry could not keep pace. Control systems, targeting systems, camouflage, maintenance and disruption of communications, the strike capability of so-called conventional weapons (a misleading term, really, and out of date) became anachronisms even before they were put into the field.

That is why, in the late eighties, production was frequently halted on new fighter planes and bombers, cruise missiles, anti-antimissiles, spy satellites, submarines, laser bombs, sonars, and radars. That is why prototypes had to be abandoned and why so much political debate  seethed around successive weapons that swallowed huge budgets and vast human energies. Not only did each innovation turn out to be far more expensive than the one before, but many soon had to be written off as losses, and this pattern continued without letup. It seemed that technological-military invention per se was not the answer, but, rather, the speed of its industrial implementation. This phenomenon became, at the turn of the century, the latest paradox of the arms race. The only way to nullify its awful drain on the military appeared to be to plan weapons not eight or twelve years ahead, but a quarter of a century in advance -- which was a sheer impossibility, requiring the prediction of new discoveries and inventions beyond the ken of the best minds of the day.

At the end of the twentieth century, the idea emerged of a new weapon that would be neither an atom bomb nor a laser gun but a hybrid of the two. Up to then, there were fission (uranium, plutonium) and fusion (thermonuclear, hydrogen-plutonium) bombs. The "old" bomb,
in breaking nuclear bonds, unleashed every possible sort of radiation: gamma rays, X-rays, heat, and an avalanche of radioactive dust and lethal high-energy particles. The fireball, having a temperature of millions of degrees, emitted energy at all wavelengths. As someone said, "Matter vomited forth everything she could." From a military standpoint it was wasteful, because at ground zero all objects turned into flaming plasma, a gas of atoms stripped of their electron shells. At the site of the explosion, stones, trees, houses, metals, bridges, and human bodies vaporized, and concrete and sand were hurled into the stratosphere in a rising mushroom of flames. "Conversion bombs" were a more efficient version of this weapon. They emitted what the strategists required in a given situation: either hard radiation -- in which case it was called a "clean bomb," striking only living things -- or thermal radiation, which unleashed a firestorm over hundreds of square miles.

The laser bomb, however, was not actually a bomb; it was a single-charge laser gun, focusing a huge part of its force into a ray that could incinerate a city (from a high orbit), for example, or a rocket base, or some other important target (such as the enemy's satellite defense screen). At the same time, the ray would turn the laser bomb itself into flaming fragments. But we will not go into more detail about such weapons, because instead of leading to further escalation, as was expected, they really marked its end.

It is worthwhile, however, to look at the atomic arsenals of twentieth-century Earth from a historical perspective. Even in the seventies, they held enough weapons to kill every inhabitant of the planet several times over. Given this overabundance of destructive might, the specialists favored a preventive strike, or making a second strike at the enemy's stockpiles while protecting their own. The safety of the population was important but second in priority.

In the early fifties, the Bulletin of the Atomic Scientists printed a discussion in which the fathers of the bomb, physicists like Bethe and Szilard, took part. It dealt with civil defense in the event of nuclear war. A realistic solution would have meant evacuating the cities and building gigantic underground shelters. Bethe estimated the cost of the first phase of such a project to be twenty billion dollars, though the social and psychological costs were beyond reckoning. But it soon became clear that even a "return to the cave" would not guarantee the survival of the population, because the arms race continued to yield more powerful warheads and increasingly accurate missiles. The science fiction of the day painted gloomy and nightmarish scenes in which the degenerate remnants of humanity vegetated in concrete, multilevel molehills beneath the ruins of gutted cities. Self-styled futurologists (but all futurologists were self-styled) outdid one another in extrapolating, from existing atomic arsenals, future arsenals even more frightful. One of the better known of such speculations was Herman Kahn's Thinking about the Unthinkable, an essay on hydrogen warfare. Kahn also thought up a "doomsday machine." An enormous nuclear charge  encased in a cobalt jacket could be buried by a nation in the depths of its own territory, in order to blackmail the rest of the world with the threat of "total planetary suicide." But no one dreamed that, with political antagonisms still persisting, the era of atomic weapons would come to an end without ushering in either world peace or world annihilation.

During the early years of the twenty-first century, theoretical physics pondered a question that was thought to be crucial for the world's continued existence: namely, whether or not the critical mass of uranides like uranium 235 and plutonium (that is, the mass at which an initiated chain reaction causes a nuclear explosion) was an absolute constant. If the critical mass could be influenced, particularly at a great distance, there might be a chance of neutralizing all warheads. As it turned out (and the physicists of the previous century had a rough idea of this), the critical mass could change. Under certain physical conditions, an explosive charge that had been critical ceased to be critical, and therefore did not explode. But the amount of energy needed to create such conditions was far greater than the power contained in all the atomic weapons combined. These attempts to neutralize atomic weapons were unsuccessful.

## III

In the 1990s a new type of missile, popularly called the ["F&F" (Fire & Forget)](https://en.wikipedia.org/wiki/Fire-and-forget), made its appearance. Guided by a programmed microcomputer, the missile sought its own target after being launched. Once activated, it was truly on its own. At the same time, "unhuman" espionage came into use, at first underwater. An underwater mine, equipped with sensors and memory, could keep track of the movements of ships sailing over it, distinguish commercial vessels from military, establish their tonnage, and transmit the information in code if necessary.

Combat readiness, in the affluent nations especially, evaporated. Young men of draft age considered such time-honored phrases as Dulce et decorum est pro patria mori to be completely ridiculous.

Meanwhile, new generations of weapons were rising in price exponentially. The airplane of the First World War was made of canvas, wood, and piano wire, with a couple of machine guns; landing gear and all, it cost about as much as a good automobile. A comparable airplane of the Second World War cost as much as thirty automobiles. By the end of the century, the price of a jet interceptor or a radar-proof bomber of the "Stealth" type was in the hundreds of millions of dollars. Aircraft for the year 2000 were expected to cost a billion apiece. At this rate, it was calculated that over the next eighty years each superpower would be able to afford only twenty to twenty-five new planes. Tanks were no cheaper. And an atomic aircraft carrier, which was like an antediluvian brontosaurus under fire, cost many billions. The carrier could be sunk by a single hit from an F&F superrocket, which could split over the target into a cluster of specialized warheads, each to strike at a different nerve center of the sea leviathan.

At this same time, the production of microchips was discontinued; they were replaced by a product of the latest genetic engineering. The strain Silocobacter wieneri (named after the creator of cybernetics, Norbert Wiener) produced, in solutions containing silicates, silver, and a secret ingredient, solid-state circuits that were smaller than fly's eggs. These elements were called "grain," and after four years of mass production a handful of them cost no more than a handful of corn. In this way, from the intersection of two curves -- the rising curve of cost for heavy weaponry and the falling curve of cost for artificial intelligence -- came the "unhumanization" of the military.

Armies began to change from living to nonliving forces. Initially, the effects of the  change were undramatic. It was like the automobile, whose inventors did not immediately come up with an entirely new shape but, instead, simply put an internal-combustion engine in a cart or carriage, with the harness removed. Similarly, the earliest pioneers of aviation gave their flying machines the wings of birds. Thanks to this kind of mental inertia, which in the military is considerable, not very radical new missiles, unmanned tanks, and self-propelled artillery were adapted for the new microsilicon "soldier," simply by reducing them in size and installing computer-controlled command modules. But this was anachronistic. The new, nonliving microsoldier required a whole new approach to tactics, strategy, and, of course, to the question of what kinds of weapons he could put to best use.

This came at a time when the world was slowly recovering from two economic crises. The first was caused by [the formation of the OPEC cartel and the big increases in the price of crude oil](https://en.wikipedia.org/wiki/1973_oil_crisis); the second, by [the collapse of OPEC and the sudden drop in the price of oil](https://en.wikipedia.org/wiki/1980s_oil_glut#OPEC). Although early nuclear-power plants were in operation, they were of no use for powering land or air vehicles. This is why the cost of heavy equipment such as troop carriers, artillery, missiles, trucks, tanks, and submarines, not to mention the cost of the newer (late-twentieth-century) types of heavy weapons, was constantly on the rise, even though by then the troop carriers had no one to transport and before long the artillery would have no one to shell.

This final phase of the military's gigantomania in weaponry gave way to a period of microminiaturization under the banner of artificial nonintelligence. Oddly enough, it was only in 2040 that the informationists, cipher theorists, and other experts expressed surprise at how their predecessors could have been so blind for so long, struggling to create artificial intelligence. After all, for the overwhelming majority of tasks performed by people in 97.8 percent of both blue- and white-collar jobs, intelligence was not necessary. What was necessary? A command of the situation, skill, care, and enterprise. All these qualities are found in insects.

A wasp of the [Sphecidae](https://en.wikipedia.org/wiki/Sphecidae) family finds herself a cricket and injects into its nervous system a poison that paralyzes but does not kill. Next she digs a burrow in the sand, sets her victim beside it, enters the burrow to make sure that it is usable -- free of dampness or ants -- then drags the cricket inside, deposits her egg in it, and flies off to repeat the process. The wasp's larva will feed on the living body of the cricket until the larva changes into a pupa. The wasp thus displays an excellent command of the situation in the choice of victim and in the anesthetic procedure she performs on it; skill in preparing an enclosure for it; care in checking the enclosure to see that conditions are suitable for her offspring; and enterprise, without which this whole series of activities could never have been carried through. The wasp may have enough nerve tissue to drive a truck from a port to a distant city or to guide a transcontinental rocket. It is only that its nervous system was programmed by natural evolution for completely different tasks.

Successive generations of information theorists and computer scientists had labored in vain to imitate the functions of the human brain in computers; stubbornly they ignored a mechanism a million times simpler than the brain, incredibly small, and remarkably reliable in its operation. Not artificial intelligence but artificial instinct should have been simulated for programming at the outset. Instinct appeared almost a billion years earlier than intelligence -- clear proof that it is easier to produce.

From studying the neurology and neuroanatomy of the mindless insect the specialists of the mid-twenty-first century quickly obtained splendid results. Their predecessors were truly blind to overlook the fact that such insects as bees, seemingly primitive creatures, nevertheless possess their own, inherited language, with which the workers in the hive inform one another of the location of newly discovered nectar. Through signal-gesture-pantomime the direction of the  path is given, the time required to reach the nectar, and even its relative quantity.

Of course, the point was not to duplicate wasps, flies, spiders, or bees in computer chips or the like; the important thing was their neural anatomy with its built-in sequences of directed behavior and programmed goals. The result was a scientific-technological revolution that totally and irreversibly transformed the battlegrounds of Earth. Until then, all arms had been fashioned to fit man; their components were tailored to his anatomy, so that he could kill effectively, and to his physiology, so that he could be killed effectively.

As so often happened, the beginnings of this complex new trend lay in the twentieth century, but at that time no one was able to combine them into a novel synthesis, because the discoveries that made possible the unhumanization of weapons systems took place in widely separated fields. Military experts had no interest in insects (except the lice, fleas, and other parasites that beset soldiers in wartime). Intellectronics engineers, who with the entomologists and neurologists studied the neurology of insects, knew nothing about military problems. And politicians, true to form, knew nothing about anything.

Thus, while intellectronics was developing microcalculators so small that they competed in size with the nerve bundles of mosquitoes and hornets, the majority of artificial-intelligence enthusiasts were still busy programming computers to carry on stupid conversations with not-too- bright people. The mammoths and dinosaurs of the computer species were beating chess masters not because they were more intelligent but only because they could process data a billion times faster than Einstein. For a long time no one imagined that all the ordinary front-line soldier needed was the skill and enterprise of a bee or a hornet. In basic military operations, intelligence and combat effectiveness are two entirely different things. (Intelligence can actually be a negative factor. In battle, the soldier's instinct for self-preservation, incomparably greater than a bee's, can interfere; the bee, on the other hand, will sting to defend its hive though the sting means its own death.) Who knows how long the old-fashioned way of thinking would have continued in the weapons industry -- the search for new conventional and unconventional instruments of warfare, the spiraling arms race -- had it not been for a few works that directed the public's attention to a remote and unusual episode in our planet's history.

## IV

Sixty-five million years ago, on the so-called C-T geological boundary (between the Cretaceous and the Tertiary), a meteorite fell on our planet. It had a diameter of about ten kilometers and contained a considerable amount of iron and iridium. Its mass is estimated to have been over three and a half trillion (3,600,000,000,000) tons. It is unclear whether it was one mass, hence an asteroid from the region between Earth and Mars, or a group of bodies forming the head of a comet. In the geological stratum of this period, iridium and rare earth metals have been discovered in amounts and concentrations not normally found in the Earth's crust. The absence of an impact crater made it difficult to prove the planetary scale of this cataclysm, since craters that appeared later (caused by meteorites a thousand times smaller) left marks on the Earth's surface that are clearly visible today. Most likely, this asteroid or comet did not strike any of the continents but landed in the open ocean -- or else the collision took place near a junction of continental plates, and the subsequent shifting obliterated the crater.

A meteor of such size and mass can easily pass through the protective layer of the atmosphere. The energy of the impact, comparable in magnitude to the energy of all the world's nuclear stockpiles (if not larger), turned that body -- or group of bodies -- into thousands of  billions of tons of dust, which the air currents spread over the entire surface of the Earth, creating a cloud so thick and long-lasting that for at least four months photosynthesis ceased in plants on all continents. Darkness reigned; the land surface, no longer heated by the sun's rays, grew much colder than did the ocean, which cooled more slowly. Nevertheless, the marine algae, one of the main sources of atmospheric oxygen, also lost their ability to carry on photosynthesis during that time. As a result, an enormous number of plant and animal species became extinct. The most spectacular extinction was that of the giant reptiles commonly called dinosaurs -- although at least several hundred other reptile species died out then, too. The catastrophe occurred at a time when the Earth's climate was gradually cooling, and the large, hairless Mesozoic reptiles found themselves in great difficulty. Even before the cataclysm, their viability had been on the wane for about a million years, as the fossil record reveals. The calcium shells of the dinosaur eggs grew thinner as the millennia passed -- testimony to the increasing hardships in feeding and to the worsening climate of the large landmasses.

Computer simulations of such an event, done back in the 1980s, verified its lethal effect on the biosphere. Strangely enough, the phenomenon to which we owe our emergence as a rational species was not introduced into any school curriculum, even though there was not the slightest doubt about the connection between the [Cretaceous-Tertiary saurocide](https://en.wikipedia.org/wiki/Cretaceous-Paleogene_extinction_event) and anthropogenesis.

Paleontological research toward the end of the twentieth century proved that the dinosaurs were warm-blooded, and that the winged varieties were covered with something very much like feathers. The mammal species that coexisted with these reptiles, having no opportunity to evolve, did not exceed the size of a rat or a squirrel. Competition on land, in the water, and in the air from the powerful, hardy reptiles was too great; the mammals were but an evolutionary footnote to the carnivorous and herbivorous vertebrates of the day.

The planetary catastrophe worked against the large animals not directly but indirectly, through the interruption of the food chain in the biosphere. When photosynthesis stopped, vegetation withered on a massive scale, and the large herbivorous reptiles of land, sea, and air could not find enough food. The predators who ate the herbivores perished for the same reason. A huge number of marine animals also died out, because in the oceans the biological carbon cycle proceeds much faster than on land, and because the surface layers of water cooled more quickly than the deeper layers. A few small reptile species did survive. But the small mammal survivors were numerous, and so, when the dust of the meteor settled and the atmosphere cleared and plant life revived, they began to differentiate, branching into many species, which after forty million years produced the line of primates from which Homo sapiens descended.

Thus the cause -- indirect but undoubted -- of rational man's emergence was a cataclysm on the C-T boundary. For our subject, however -- the military evolution of civilization -- it is the consequences of this event, so long overlooked, that are important. The fact is that the ones who suffered least on the C-T boundary were the insects! Before the catastrophe there were about three-quarters of a million insect species; a short time afterward, there were still at least seven hundred thousand, and social insects like ants, termites, and bees survived the cataclysm practically unimpaired. This leads us to conclude that cataclysms are survived most easily and with the greatest probability by small or very small animals with an insectile anatomy and physiology.

Nor should one consider it an accident that insects are generally much less susceptible to the lethal effects of radioactivity than the so-called higher animals, the vertebrates. Paleontology speaks unequivocally. A catastrophe that unleashed the destructive force of a global atomic war killed every one of the large animals but did little damage to the insects and did not touch the  bacteria. This shows that the greater the destructive action of an elemental force or technological weapon, the smaller must a system be in order to survive it unharmed. Thus the atomic bomb demanded the dispersal not only of whole armies but also of individual soldiers. General staffs considered dispersing their armies, but in the twentieth century the idea of reducing a soldier to the size of an ant or a wasp found no expression outside the pages of fantasy. A human being couldn't be reduced or dispersed! In those days much thought was given to soldier-automatons -- humanoid robots -- a naive anthropomorphism. Yet heavy industry was already undergoing unhumanization, and the robots that replaced people on the assembly lines were not remotely humanoid. They were the enlargement of selected, functional parts of the human being: a computer "brain" with one huge steel hand assembling a car chassis, or a system with a hammer-fist, or with a laser-finger to weld the bodies. These devices worked like eyes and hands but did not look like eyes or hands. But large and heavy robots such as these could not be put on the battlefield, where they would immediately become the target of accurate, self-guided, intelligent missiles.

So it was not humanoid automata that formed the new armies but synthetic insects (synsects) -- ceramic micro[crustacea](https://en.wikipedia.org/wiki/Crustacean), titanium [annelids](https://en.wikipedia.org/wiki/Annelid), and flying pseudo-[hymenoptera](https://en.wikipedia.org/wiki/Hymenoptera) with [nerve centers made of arsenic](https://en.wikipedia.org/wiki/Gallium_arsenide) compounds and with stingers of heavy, fissionable elements. Most of this "nonliving micropersonnel" could, at the first warning of an atomic attack, dig deep into the ground and then crawl out after the explosion, maintaining combat functions even in an environment glowing with terrible radioactivity, because these soldiers were not only microscopic but nonbiological. The flying synsect combined plane, pilot, and missile in one miniature whole. But the operating unit was the microarmy, which possessed superior combat effectiveness only as a whole (just as a colony of bees was an independent, surviving unit while a single bee was nothing).

Because the battlefield was constantly exposed to atomic attack, which not only destroyed combat forces but also disrupted all communications between the various weapons systems (and also between the weapons and their command centers), there arose nonliving microarmies of many types. These were based on two opposing principles.

According to the first -- the principle of autonomy -- an army proceeded like a column of ants, or a wave of microbes, or a swarm of locusts. The last analogy is particularly apt. The locust, as we know, is simply a biological variety of the common grasshopper (not a separate species); even in clouds numbering hundreds of billions of specimens (still greater numbers have been observed from planes) it is not directly harmful to humans.[^1] Nevertheless, the sheer mass of a locust cloud can cause a train to derail, turn day into night, and paralyze all movement. (Even a tank, entering a cloud of locusts, will begin to slip as it crushes the insects into a pulp of ichor and grease and will bog down as in a quagmire.) The nonliving, synthetic "locust" was incomparably more lethal, since it was made that way by its designers. It possessed a preprogrammed autonomy, so that communication with a command center was unnecessary. The pseudo-locust could be destroyed, of course, by an atomic attack, but this would have an effect like that of shooting at clouds with nuclear weapons: great holes would open, only to fill again with more cloud.

[^1]: If one disregards the chief destructive result of such visitations -- that is, the total loss of vegetation and cultivated crops.

According to the second principle of the new military -- telotropism -- the microarmy was one giant flowing or flying aggregate of self-assembling elements. It started out dispersed,  approaching its objective from many different directions, as strategy or tactics demanded, in order to concentrate into a preprogrammed whole on the battlefield. For this fighting material did not leave the factory in final shape, ready for use, like tanks or guns loaded on a railroad flatcar; the mechanisms were microproductive blocks designed to fuse together into a war machine at the designated place. For this reason, such armies were called "self-bonding."

The simplest example was a self-dispersing atomic weapon. Any missile launched from land, ship, or submarine could be destroyed from space by a satellite laser. But it was impossible to destroy gigantic clouds of microparticles carrying uranium or plutonium that merged into a critical mass only at the target. En route to the target, they were so dispersed as to be indistinguishable from fog or dust.

The competition between old and new weapons was brief: massive, armored equipment could not withstand the attacks of the microarmies. Just as germs invisibly invade an organism to kill it from within, so the nonliving, artificial microbes, following the tropisms built into them, penetrated the gun barrels, cartridge chambers, tank and plane engines. They corroded the metal catalytically, or, reaching the powder charges or fuel tanks, blew them up. What could even the bravest soldier, carrying grenades, a machine gun, a bazooka, or any other firearm, do against a nonliving, microscopic enemy? He would be like a doctor trying to fight the bacteria of cholera with a hammer or a revolver.

Amid a swarm of self-guided, programmed microarms, a man in uniform was as helpless as a Roman legionary with sword and shield against a hail of bullets. In the face of special types of biotropic microarms capable of destroying everything that lived, human beings had no choice but to abandon the battlefield, for they would be killed in seconds.

Even in the twentieth century, the tactic of fighting in close ranks gave way to the spreading of troops, and in a mobile war the spreading was still greater. But the front lines still existed, separating friend from foe. Now such boundaries disappeared completely.

A microarmy could easily penetrate all systems of defense and go deep into enemy territory. It had no more trouble accomplishing this than did rain or snow. Meanwhile, high-powered nuclear weapons were proving more and more useless on the battlefield. Imagine, if you will, an attempt to combat a virus epidemic with thermonuclear bombs. It was possible, of course, to scorch a large territory down to a depth of fifty feet, turning it into a vitrified, lifeless desert. But what good was that if on that expanse, one hour later, a military rain began to fall and from it there crystallized detachments of shock troops? Hydrogen bombs were expensive. One didn't hunt in warships for leeches or sardines.

The greatest problem in the unhuman stage of military history was that of distinguishing friend from foe. This task had been accomplished, in the twentieth century, by means of electronic systems working on a password principle. Challenged by radio, a plane or an unmanned missile either radioed the right answer or else was attacked as an enemy craft. This ancient method now proved useless. The new weapon-makers again borrowed from the biosphere -- from plants, bacteria, and insects.

Recognition duplicated the methods of identification used among living species: their immunology -- the struggle of antigen with antibody -- tropisms, protective coloration, camouflage, and mimicry. The nonliving weapon might imitate (extremely well) floating dust specks or pollen, or gnats, or drops of water. But under that mask lay a corrosive or lethal agent.

It should be pointed out that although I am using metaphors from entomology in talking about attacks of artificial locusts or other insects, I do so as a twentieth-century person would describe, to the contemporaries of Vasco Da Cama or Christopher Columbus, a modern city with its automobile traffic. He would speak of carriages and wagons without horses; he would  compare airplanes to birds made of metal. In this way he would evoke in the minds of his listeners images that had some connection with reality, albeit an imperfect one. A carriage rolling on large, thin wheels, with high little doors and a dropped step, with a box for the coachman and places at the back for the servants, is not a Fiat or a Mercedes. By the same token, the twenty-first-century synsect weapon is not a swarm of insects just like the ones in an entomologist's atlas, only made of metal.

Some of the pseudo-insects could pierce the human body like bullets; others could form optical systems to throw sunlight over wide areas, altering the temperature of large air masses so as to produce heavy rainfall or fair weather, according to the needs of the campaign. There existed "meteorological insects" corresponding to nothing we know today. The endothermic synsects, for example, absorbed large quantities of energy for the sole purpose of causing a sudden drop in temperature over a given area, resulting in a thick fog or the phenomenon known as an inversion. Then there were synsects able to concentrate themselves into a single-use laser beamer; they replaced the artillery of the previous century -- although one can hardly speak of replacement, since artillery as we understand it would have been of as much use on the battlefield as slings and catapults. New weapons dictated new conditions of combat and, therefore, new strategy and tactics, both totally unhuman.

For those who loved the uniform, the flag, the changing of the guard, standing at attention, drill, medals, and bayonet charges, the new era of war was an affront to their noble ideals, a mockery, a disgrace! The experts of the day called the new military science an "upside-down evolution," because in nature what came first were the simple, microscopic systems, which then changed over the eons into larger and larger life forms. In the military evolution of the postnuclear period, the exact opposite took place: microminiaturization.

The microarmies developed in two stages. In the first stage, the unhumaned microweapons were still designed and built by people. In the second stage, microsoldiers were designed, combat-tested, and sent to be mass-produced by "construction battalions" of nonliving microdesigners.

A phenomenon known as "sociointegrative degeneration" displaced humans first from the military and later from the weapons industry. The individual soldier degenerated when he ceased to be an intelligent being with a large brain and grew increasingly small and therefore increasingly simple, or when he became disposable, a "single-use soldier". (Some of the antimilitarists had maintained, long before, that modern warfare's high mortality rate made "single-use soldiers" of all the combatants, with the exception of the top-ranking officers.) In the end, a microfighter had as much brain as an ant or a termite.

A greater role, then, was assumed by the pseudo-sociointegrative collective of microsoldiers. Each nonliving army was incomparably more complex than a beehive or an anthill. In internal structure and interrelationships it was more akin to an ecological unit in nature -- that is, to those pyramids of plant and animal species that coexist in a specific region or habitat in evolutionary equilibrium, with their antagonisms and symbioses forming a complex network of interdependencies.

It is easy to see that in such an army there was nothing for noncommissioned officers to do. A corporal or a sergeant, even a general, could not lead a division of such an army. To grasp the whole picture, as complex as nature itself (although quite dead), the wisdom of a university senate would not have sufficed -- even for a mere inspection, much less an actual campaign. Besides the impoverished nations of the Third World, therefore, those who suffered the most from the great military revolution of the twenty-first century were the officer cadres.

The twentieth century had already begun the process of destroying them, dispensing with  swords, three-cornered hats, and gorgeous uniforms. The final blow, however, was dealt in the twenty-first century by the army's pseudo-insect evolution -- or, rather, involution. The cruel pressure to unhumanize the armies did away with the picturesque traditions of war games, the pageantry of parades (a marching locust, unlike a procession of tanks or rockets, is not a grand sight), the bayonet drills, the bugle calls, the flag raisings and lowerings, the roll calls, the whole rich fabric of barracks life. For a time, high-ranking command positions were kept for people, but not for very long.

The strategical-numerical superiority of the computer-produced echelons finally forced even the most competent of commanders, including field marshals, into retirement. A tapestry of ribbons and medals on the chest was no protection against being put out to pasture. In various countries, at that time, a resistance movement developed among career officers. In the desperation of unemployment, they even joined the terrorist underground. It was a malicious trick of history -- no one deliberately planned it -- that these insurrections were crushed by means of micro-spies and minipolice built on the model of a particular cockroach.

This roach, first described in 1981 by an eminent American neuroentomologist, has at the end of its abdomen fine hairs that are sensitive to even the slightest stirring in the air. Connected to a special dorsal nerve bundle, the hairs enable the roach to detect the approach of an enemy, even in complete darkness, and so to flee instantly. The counterparts to these hairs were the electronic picosensors of the minipolicemen who concealed themselves in cracks in old wallpaper at the rebel headquarters.

But things were not so good in the affluent nations, either. It was impossible to go on with the old political games. The line between war and peace, increasingly blurred for some time, was now obliterated entirely. The twentieth century had discarded the ritual of formal declarations of war, introducing the sneak attack, the fifth column, mass sabotage, cold war, and war by proxy, but this was only the beginning of the erosion of distinctions.

A world with two mutually exclusive political conditions -- war or peace -- changed into a world in which war was peace and peace became war. In the past, when covert agents were all human beings, they hid their mischief behind various masks of respectability and virtue. They infiltrated religious and social movements, including even senior citizens' choral societies and organizations of matchbox collectors. Later, however, anything could be a covert agent: a nail in the wall, a laundry detergent. Military espionage and sabotage flourished. Since human beings were no longer a real political or military force, there was no point in winning them over with propaganda or in talking them into collaborating with the enemy. Unable to write here about the political changes as much as they warrant, I will convey in a few words the essence of what took place.

Even in the previous century the politicians of the parliamentary countries could not keep up with everything that was going on in their own countries -- much less in the world -- and so they had advisers. Every political party had its experts. But the advisers of the different parties said completely different things. With time, computer systems were brought in to help; too late, people realized they were becoming the mouthpieces of their computers. They thought they were the ones doing the reasoning, drawing independent conclusions based on data supplied by computer memory; but in fact they were operating with material preprocessed by the computer centers, and that material was determining human decisions.

After a period of some confusion, the major parties concluded that the expert advisers were dispensable middlemen; from then on, each party headquarters had a main computer. In the second half of the twenty-first century, when a party took power its computer was sometimes given the post of minister without portfolio (a computer did not need a portfolio anyway), and the  pivotal role in such democracies was played by programmers. The programmer took a loyalty oath, but that did not prove very effective. Democracy, many warned, was becoming computerocracy.

For this reason, too, espionage and counterespionage turned away from politicians and environmental-protection groups (of which there were few, since by then there was not much left to save) and infiltrated the computation and decision centers. Of course, no one could absolutely prove that this was so. Some political scientists maintained that if nation A took over the computerocracy of nation B, and nation B did the same to nation A, then international equilibrium would again be restored. What had become everyday reality could no longer be described in terms of the old, traditional politics, or even by common sense, which still distinguished between natural phenomena, like a hailstorm, and man-made ones, like a bombing attack.

Elections were still held for political parties, but each party boasted of having not the best economic program but the best computer, one that would solve all social ills and problems. Whenever two computers disagreed, the government ostensibly decided; but in reality the arbiter was another computer. It will be better to give a concrete example.

For several decades the three major branches of the United States armed forces, the army, navy, and air force, had been struggling among themselves for supremacy. Each tried to get the largest share of the military allocation in the budget at the expense of the others. Each kept its newest weapons secret from the others. To learn these secrets was one of the main tasks of the President's advisers. Each service had its own headquarters, its own security system, its own codes, and -- obviously! -- its own computer. Each kept cooperation with the others to the absolute minimum, just enough so the government wouldn't fall apart. Indeed, the main concern of each successive administration was to see that a minimum of unity was maintained in the government of the country and the conduct of foreign policy.

Even in the previous century no one knew what the real military strength of the United States was, because that strength was presented to the people differently, depending on whether a White House spokesman was speaking or an opposing presidential candidate. But nowadays the devil himself could not make head or tail of the situation.

Meanwhile, in addition to computer rule, which was gradually replacing natural, human rule, there appeared certain phenomena that once would have been called natural; but now no one knew by what or by whom they were caused, if indeed they were caused by anything or anyone at all. Acid rain had been known in the twentieth century. But now there were rains so corrosive that they destroyed roads, power lines, and factory roofs, and it was impossible to determine whether they were caused by pollution or by enemy sabotage. It was that way with everything. Livestock were stricken, but was the disease natural or artificial? The hurricane that ravaged the coast -- was it a chance thing, or was it engineered by an invisible swarm of micrometeorological agents, each as small as a virus, covertly diverting ocean air masses? Was the drought natural -- however murderous -- or was it, too, caused by a skillful diversion of the rain clouds?

These calamities beset not just the United States but the entire world. Again, some saw in this evidence of their natural origin; others, again, were convinced that the reason they were pandemic was that all countries now had at their disposal unhuman means of striking at any distance and were inflicting damage on one another, while declaring officially that they were doing nothing of the sort. Caught in the act, a saboteur could not be cross-examined: synsects and artificial microbes were mute. Meteorological counterintelligence, seismic espionage, reconnaissance teams of epidemiologists, geneticists, and even hydrographers had their hands full. An ever larger share of world science was enlisted in this military intelligence work. Hurricanes, crop failures, rising mortality rates in cattle, and even meteor showers were suspected of being intentional. (Note, by the way, that the idea of guiding asteroids to fall on enemy territory, causing terrible devastation, had arisen in the twentieth century and was considered interesting.)

New disciplines were taught in the military academies: crypto-offensive and crypto-defensive strategies, the cryptology of counter-counterintelligence (the covert enticement-deception of agents raised to the next power), applied enigmatics, and finally "cryptocryptics" which presented in a secret manner the secret use of weapons so secret that there was no way anyone could tell them from innocent phenomena of nature.

Blurred, also, was the distinction between real and spurious hostilities. In order to turn its people against another nation, a country would produce on its own territory "natural" catastrophes so obviously artificial that its citizens were bound to believe the charge that the enemy was responsible. When it came out that a certain large and wealthy nation, in offering aid to those that were underdeveloped and overpopulated, supplemented the provisions it sold (cheaply) of sago, wheat, corn, and potato flour with a drug that diminished sexual potency, the Third World became enraged. This was now an undercover, antinatural war.

Thus peace was war, and war peace. Although the catastrophic consequences of this trend for the future were clear -- a mutual victory indistinguishable from universal destruction -- the world continued to move in that fatal direction. It was not a totalitarian conspiracy, as Orwell once imagined, that made peace war, but the technological advances that effaced the boundary between the natural and the artificial in every area of human life, even in extraterrestrial space.

When there is no longer any difference between natural and artificial protein, or between natural and artificial intelligence -- say the theoreticians of knowledge, the philosophers -- then neither can one distinguish a misfortune that is intentional from one for which no one is to blame.

As light, pulled irresistibly into the heart of a stellar black hole, cannot escape that gravitational trap, so humanity, pulled by the forces of mutual antagonism into the heart of matter's secrets, fell into the trap of technology, a trap of its own making. The decision to invest everything in new weapons was not made by governments, statesmen, generals, corporate interests, or pressure groups, but by the ever-growing fear that someone else would be first to hit upon the discoveries and technologies affording the ultimate advantage. This paralyzed traditional politics. The negotiators at summit meetings could not negotiate, because their willingness to relinquish a new weapon would only indicate, in the eyes of the other side, that they had another, newer weapon up their sleeve...

By now the impossibility of disarmament had been proved mathematically. I have seen the mathematical model of the so-called general theory of conflicts; it shows why arms talks cannot produce results. At summit meetings certain decisions are reached. But when it takes longer to reach a decision promoting peace than it does to develop the kind of military innovations that radically change the very situation under negotiation, then any decision, at the moment of its acceptance, is an anachronism.

It is as if the ancients had debated so long about banning their "[Greek fire](https://en.wikipedia.org/wiki/Greek_fire)" that by the time they agreed to ban it, [Berthold Schwarz](https://en.wikipedia.org/wiki/Berthold_Schwarz) had appeared with his gunpowder. When one decides "today" about something that existed "yesterday," the decision moves from the present into the past and thereby becomes an empty game.

It was this that finally, at the end of the twenty-first century, forced the world powers into a new type of agreement, an agreement that opened up a new era in the history of the human race. But that is a subject that belongs to the twenty-second century and therefore lies outside the scope of these remarks. Later, if I am able, I will devote a separate discussion to it -- describing the next chapter of general history, a remarkable chapter, in which Earth, emerging from the era of antagonisms, truly frees itself from one technological trap, but steps into another, as if her destiny is to go forever from the frying pan into the fire.

## Excerpt from *Peace on Earth* (1985)

On my return home I found a fat envelope in my mailbox. It contained a book with the title _The Unhumanization of Weapon Systems in the Twenty-first Century _or _Upside-down Evolution. _The author's name, Meslant, told me nothing. It was a heavy book, full of graphs and tables. Having nothing better to do, I sat down and began to read. On the first page, before the introduction, was an epigraph in German:

> Aus Angst und Not
> 
> Das Heer ward tot.
> 
> --- Eugen von Wahnzenstein

\[From fear and dread / The army fell dead.\]

The author presented himself as an expert in contemporary military history. His subject, the new pacifism at the close of the twentieth century: it was prosperity and cowardice that gave birth to the unhumanization of war. People were increasingly reluctant to be fired upon, and this loss of martial spirit was directly proportional to the standard of living. The youth of wealthy nations weren't interested in the noble motto _Duke et decorum est pro patria mori_. And it was just at that time that prices began falling in the intellectronics industry. Microprocessing elements called _chips_ were replaced by _corn_, the product of the genetic engineering of a culture of artificial microbes, mainly _Silicobacterium logicum wieneri_, named after the father of cybernetics. A handful of these elements cost no more than a handful of barley. Thus artificial intelligence grew cheap, yet the price of new weapons increased geometrically. In the first world war a plane cost as much as a car, in the second as much as twenty, and by the end of the century it was six hundred times more. It was calculated that in seventy years a superpower would be able to afford from eighteen to twenty-two planes. The falling curve of the cost of intelligence and the rising curve of the cost of weapons intersected, and at that point began the unhumanization of the armies. The military became unliving. At which juncture the world went through two crises. The first was when the price of oil soared, the second when shortly thereafter it plunged. The classic rules of economics went out the window, but few understood what was happening, or that the image of a soldier in uniform and helmet charging with bayonet was becoming as distant as the medieval knight in armor. Out of inertia the engineers continued to make big-gauge weapons for a while: tanks, cannon, carriers, and other fighting machines to be used by men, though already these could have gone into battle themselves, without them. Then followed a phase of accelerated miniaturization. Until now all weaponry had been fashioned to fit man: Tailored to his anatomy and physiology, so that he could kill and be killed.

As is usually the case in history, no one saw what lay ahead, for the discoveries which were to make possible the unhumanization of weapons took place in fields of science far from one another. Intellectronics produced microcomputers as cheap as grass, and neuroentomology finally solved the riddle of social insects who live and work together, communicating in their own language, even though bees, for example, have a nervous system 380,000 times smaller than a human brain. The intelligence of a bee is quite sufficient for a foot soldier, as military prowess and intelligence are two different things, at least on the battlefield. The major factor in the push for miniaturization was the atom bomb. The need to miniaturize came from simple facts, but facts that lay outside the military knowledge of the day. Seventy million years ago a huge meteor hit Earth and chilled its climate for centuries, making the dinosaurs defunct but hardly bothering insects and not even touching bacteria. The lesson of paleontology was clear: the greater the destructive force, the smaller the systems that escape it. The atom bomb required the _particularization_ of both soldier and army. But in the twentieth century the idea of making soldiers the size of ants was only a fantasy. You could not reduce people in size or diffuse them. So thought was given to robot soldiers, humanoid, though even then that was a naive anachronism. Industry was unhumanizing itself, but the robots who replaced workers on the assembly line were not made in the likeness of men; they were, rather, human _parts_ selected and enlarged: a brain with a big steel hand or a brain with eyes. But giant robots had no place on an atomic battlefield. So radioactive synsects (synthetic insects) were developed, and ceramic shellfish, and titanium worms able to burrow in the earth and come out after the blast. Flying synsects were airplane, pilot, and missiles all in one tiny entity. The operational unit became a _microarmy_, fighting only as a whole, much as a swarm of bees acts as a unit to survive while an individual bee is nothing. Thus microarmies of many, kinds were made, on two opposing principles. An army based on the principle of independence proceeded like a column of ants or a cloud of germs or hornets. An army based on the principle of _teletopism_, however, was an enormous flying or crawling collection of self-assembling elements; according to need, tactical or strategic, it could reach its target in extreme attenuation only to condense there into its programmed whole. The simplest example was the self-dispersing atomic warhead. An ICBM could be tracked, from space by satellite or from Earth using radar; but it was impossible to detect a cloud of infinitesimal particles of uranium or plutonium at very low density, which finally would converge and reach critical mass at its target, a factory or an enemy city.

For a while the old and new weapons coexisted, but the massive machines soon succumbed to the invisible micro. As germs secretly enter an animal organism and kill it from within, so did these unliving microbes penetrate cannon barrels, shell chambers, the engines of tanks and planes, and eat through metal, and detonate the ammunition inside. What could a brave, grenade-carrying soldier do against a microscopic, unliving adversary? He would be like a doctor trying to fight a virus with a hammer. Against an autonomous cloud programmed to destroy all things biological a man in uniform was as helpless as a Roman legionary standing with sword and shield before a rain of bullets.

Even in the twentieth century the tactic of fighting in closed ranks was replaced by the spreading out of troops, but there were still front lines. Now there were none. Microarmies easily penetrated all defenses. Nuclear weapons were ineffective combatting that viral contagion. The cost of a warhead, moreover, cannot be considerably greater than the value of its target. One doesn't use a destroyer to go after leeches.

The most vexing problem in this unhumanized stage of man's struggle with man turned out to be that of telling friend from foe. In the past it had been done by electronics, using the password principle. Challenged by radio waves, a plane or missile either transmitted back the correct answer or was attacked. This twentieth-century method became obsolete. Now the makers of arms borrowed from the plants and animals, from bacteria. For the recognition process they imitated the ways of living species: immune systems, the duel of antigen and antibody, tropism, mimicry, protective coloration, camouflage. A micro-weapon might pretend to be an innocent microorganism, or the fluff of a plant, a piece of pollen, but beneath that exterior lay corrosive death. The significance of informational combat also increased -- not in the sense now of propaganda but as the invasion of enemy communications, to paralyze it or, as in the case of the atomic locust-cloud, to force premature condensation to critical mass before it reached its target. The author of the book discussed the cockroach, which was the prototype for one kind of micro-soldier. On its abdomen the cockroach has very fine hairs. When they are moved by the air, the insect flees, because these sensors are wired directly to its rear nerve ganglion, and they can distinguish between a draft and the disturbance caused by a predator.

As I read, I felt pity for the champions of uniforms, flags, and medals for bravery: the new era of warfare must have been anathema to their high ideals. The audior used the term _upside-down evolution_, because in the beginning of life there were microscopic systems which slowly changed into larger systems, while this military evolution proceeded the other way, microminiaturization, and the great human brain was replaced by mechanical insect ganglia. Microarmies arose in two steps. First, the designers and builders were still human; then the unhumanized divisions were conceived, battle-tested, and put into mass production by computer systems that were equally nonhuman. People were eliminated from the military and then from the weapons industry by a phenomenon called "sociointegrational degeneration." The individual soldier underwent degeneration: he became smaller and simpler. In the end he had the intelligence of an ant or termite. But the _collective_ of these tiny warriors assumed a greater role. The nonliving army was far more complex than a beehive or ant hill; it was more like a biotope in nature, an ecosystem, a subtle equilibrium between competitive, antagonistic, and symbiotic species. A sergeant or corporal in such an army obviously had nothing to do. To grasp the whole picture, merely to inspect the troops, not even the brain power of an entire university would suffice. Thus officers as well as poor Third World countries did not fare well during the great military revolution of the twenty-first century. The irresistible momentum of army unhumanization destroyed the lofty traditions of maneuvers, marches, drills, changing the guard, and regalia. For a while but alas not for long, it was possible to preserve the highest ranks for people, but the strategy-computational superiority of the computerized echelons of command finally put even the most corpulent leaders, including four-star generals, out of work. A chest of ribbons and medals was no protection from early retirement. These officers, facing permanent unemployment -- for they could do nothing else -- revolted, forming an underground terrorist movement. The crushing of this revolt with the use of microspies and minipolice built on the abovementioned cockroach principle was a grim chapter in our history, because neither cover of dark nor mist nor any kind of camouflage could save those desperate traditionalists loyal to the ideas of Achilles and Clausewitz.

As for the poor countries, they could go on fighting as before, using live people, but only against opponents as anachronistic as themselves. Those who couldn't automate militarily had to sit quietly in the corner.

But it wasn't fun for the rich countries either. The old political games went out the window. The line separating war and peace, having long been blurry, was now completely erased. The twentieth century had dispensed with the formal declaration of war and introduced the fifth column, sabotage, cold war, and war by proxy, but that was only the beginning. Summit meetings for disarmament pursued mutual understanding and a balance of power but were also held to learn the strengths and weaknesses of the enemy. The world of the war-or-peace alternative became a world in which war was peace and peace war. First, wide-range subversive activity was conducted under the mask of official peace: the infiltration of political, religious, and social movements, even such worthy movements as those to protect the environment; the infiltration also of the culture and mass media, taking advantage of the illusions of the young and the conservatism of the old. Then covert military activity intensified to the point of being overt, except that it was invisible. Acid rain had been known in the twentieth century; now rain fell that was so corrosive, it destroyed the roofs of houses and factories, roads, electrical lines, but no one knew whether this was pollution or the enemy sending poison clouds their way. It was thus with everything. Farm animals died in epidemics that could have been natural or intentional. A storm that flooded the coast might have been an act of God or the clever redirection of a hurricane at sea. A drought -- a normal disaster, or one caused by the secret switching of heavy clouds with light. With seismic, meteorological, and epidemiological counterespionage and reconnaissance the scientists had their hands full. More and more of the scientific community became involved with intelligence work, yet the results of their research grew less and less clear. The tracking down of saboteurs was child's play in the days when they were human; but now, when the suspect was a hurricane or hailstorm, or a crop or cattle disease, or the rise in infant mortality or cancer rate, or even a meteor (the twentieth century had already considered the idea of aiming an asteroid at enemy territory), life became intolerable. Intolerable not only for the man on the street but also for heads of state, who were helpless and confused, and their advisors no less. The military academies added new courses such as cryptotactics, cryptocountering (that is, taking counterespionage to the _n_-th power), crypto field theory, and finally cryptocryptics, the secret study of the secret use of secret weapons indistinguishable from natural phenomena.

To blacken the enemy, one could fake a natural disaster in one's own country -- in a way that made it obvious it was not natural. Also it was proved that certain rich nations, helping those less fortunate, put a drug into the supplies of wheat, corn, and cocoa it sold (cheaply), which caused impotence. This was, then, a secret war of birth control. Although the catastrophic consequence of such escalation was obvious -- wherein victory was equivalent to defeat for both sides -- the politicians continued with business as usual, concerned more about the voters than the future, making fuzzy promises and being increasingly less able to affect the course of real events. War was peace, not from Orwell's totalitarian doublethink but because of a technology that erased the boundary between natural and artificial in every aspect of human life and its environment.

Where there is no difference, wrote the author, between natural and artificial protein or between natural and artificial intelligence, misfortunes caused deliberately cannot be distinguished from those caused by no one. Just as light that falls into a black hole cannot pull itself out of that gravitational trap, so humanity at war, reaching the secrets of matter, cannot leave the trap of technology. It wasn't the governments, heads of state, monopolies, generals, or pressure groups that made the decision to invest everything in the new arms, it was fear, fear that the Other Side would discover, invent, and develop first. Traditional politics were useless. Negotiators could negotiate nothing, because the offer to give up a new weapon only meant, for the other side, that you had a weapon that was even newer. I turned to a mathematical model of conflict theory which showed why further summit meetings were a waste of time. At such meetings, agreements were reached. But it took longer to reach an agreement than for a new development to change radically the situation on which that agreement was based, thus making it an immediate anachronism. The act of reaching an agreement, then, was an empty game of appearances. This was what compelled the world powers to accept the Geneva Agreement: an exodus of weapons to the moon. The world breathed a sigh of relief, but not for long, because fear returned -- now as the specter of the nonhuman invasion of Earth by the moon. So there was no task more urgent than to pierce the mystery of the moon.

With these words the chapter ended. There were a few dozen pages left in the book, but they wouldn't turn. As if they were glued. Stuck together with bookbinder's glue, I thought. I couldn't separate them, so finally I took a knife and slid it carefully between the pages. The first page was blank, but where the knife touched it, letters formed. I rubbed the paper with the knife until I obtained the following message: "Are you ready to assume this burden? If not, put the book back in the envelope! If yes, turn the page!"

The next page was also blank. I ran the blade from top to bottom and eight numbers appeared, in groups of two with hyphens between them like a telephone number. I separated the remaining pages but there was nothing on them. "A curious way to recruit Savers of the World!" I thought. At the same time I began to suspect what lay in store. I closed the book but it opened again by itself at the page with the numbers. Nothing was left for me but to pick up the phone and dial.

## Metadata {.appendix}

Originally published as *Waffensysteme des 21. Jahrhunderts oder The Upside Down Evolution*, in German. Published in English in 1986 in *One Human Minute*, which is a collection of 3 book reviews of 3 fictitious books.

The excerpt is from the novel [*Peace on Earth* (1985)](https://en.wikipedia.org/wiki/Peace_on_Earth_(novel)).
