<!DOCTYPE html>
<html xmlns="http://www.w3.org/1999/xhtml" lang="en" xml:lang="en"><head>

<meta charset="utf-8">
<meta name="generator" content="quarto-1.7.32">

<meta name="viewport" content="width=device-width, initial-scale=1.0, user-scalable=yes">

<meta name="author" content="Yuxi Liu">
<meta name="dcterms.date" content="2025-04-18">
<meta name="description" content="To win (?) a twitter argument, we calculated the energetic cost of O’Neil habitat per person. Oddly, it is just affordable by modern standards, ~0.72 million USD per person. Let it be known that the SF housing crisis is cheaper to solve by building O’Neil cylinders.">

<title>The cost of O’Neil habitation – Yuxi on the Wired</title>
<style>
code{white-space: pre-wrap;}
span.smallcaps{font-variant: small-caps;}
div.columns{display: flex; gap: min(4vw, 1.5em);}
div.column{flex: auto; overflow-x: auto;}
div.hanging-indent{margin-left: 1.5em; text-indent: -1.5em;}
ul.task-list{list-style: none;}
ul.task-list li input[type="checkbox"] {
  width: 0.8em;
  margin: 0 0.8em 0.2em -1em; /* quarto-specific, see https://github.com/quarto-dev/quarto-cli/issues/4556 */ 
  vertical-align: middle;
}
/* CSS for syntax highlighting */
html { -webkit-text-size-adjust: 100%; }
pre > code.sourceCode { white-space: pre; position: relative; }
pre > code.sourceCode > span { display: inline-block; line-height: 1.25; }
pre > code.sourceCode > span:empty { height: 1.2em; }
.sourceCode { overflow: visible; }
code.sourceCode > span { color: inherit; text-decoration: inherit; }
div.sourceCode { margin: 1em 0; }
pre.sourceCode { margin: 0; }
@media screen {
div.sourceCode { overflow: auto; }
}
@media print {
pre > code.sourceCode { white-space: pre-wrap; }
pre > code.sourceCode > span { text-indent: -5em; padding-left: 5em; }
}
pre.numberSource code
  { counter-reset: source-line 0; }
pre.numberSource code > span
  { position: relative; left: -4em; counter-increment: source-line; }
pre.numberSource code > span > a:first-child::before
  { content: counter(source-line);
    position: relative; left: -1em; text-align: right; vertical-align: baseline;
    border: none; display: inline-block;
    -webkit-touch-callout: none; -webkit-user-select: none;
    -khtml-user-select: none; -moz-user-select: none;
    -ms-user-select: none; user-select: none;
    padding: 0 4px; width: 4em;
  }
pre.numberSource { margin-left: 3em;  padding-left: 4px; }
div.sourceCode
  {   }
@media screen {
pre > code.sourceCode > span > a:first-child::before { text-decoration: underline; }
}
</style>


<script src="../../../site_libs/quarto-nav/quarto-nav.js"></script>
<script src="../../../site_libs/clipboard/clipboard.min.js"></script>
<script src="../../../site_libs/quarto-search/autocomplete.umd.js"></script>
<script src="../../../site_libs/quarto-search/fuse.min.js"></script>
<script src="../../../site_libs/quarto-search/quarto-search.js"></script>
<meta name="quarto:offset" content="../../../">
<link href="../../../img/favicon.ico" rel="icon">
<script src="../../../site_libs/quarto-html/quarto.js" type="module"></script>
<script src="../../../site_libs/quarto-html/tabsets/tabsets.js" type="module"></script>
<script src="../../../site_libs/quarto-html/popper.min.js"></script>
<script src="../../../site_libs/quarto-html/tippy.umd.min.js"></script>
<script src="../../../site_libs/quarto-html/anchor.min.js"></script>
<link href="../../../site_libs/quarto-html/tippy.css" rel="stylesheet">
<link href="../../../site_libs/quarto-html/quarto-syntax-highlighting-37eea08aefeeee20ff55810ff984fec1.css" rel="stylesheet" class="quarto-color-scheme" id="quarto-text-highlighting-styles">
<link href="../../../site_libs/quarto-html/quarto-syntax-highlighting-dark-2fef5ea3f8957b3e4ecc936fc74692ca.css" rel="stylesheet" class="quarto-color-scheme quarto-color-alternate" id="quarto-text-highlighting-styles">
<link href="../../../site_libs/quarto-html/quarto-syntax-highlighting-37eea08aefeeee20ff55810ff984fec1.css" rel="stylesheet" class="quarto-color-scheme-extra" id="quarto-text-highlighting-styles">
<script src="../../../site_libs/bootstrap/bootstrap.min.js"></script>
<link href="../../../site_libs/bootstrap/bootstrap-icons.css" rel="stylesheet">
<link href="../../../site_libs/bootstrap/bootstrap-c590cb3103796f9f406a17afdd3881b8.min.css" rel="stylesheet" append-hash="true" class="quarto-color-scheme" id="quarto-bootstrap" data-mode="light">
<link href="../../../site_libs/bootstrap/bootstrap-dark-493ec8732bc442be923a7677f0a4f8b4.min.css" rel="stylesheet" append-hash="true" class="quarto-color-scheme quarto-color-alternate" id="quarto-bootstrap" data-mode="dark">
<link href="../../../site_libs/bootstrap/bootstrap-c590cb3103796f9f406a17afdd3881b8.min.css" rel="stylesheet" append-hash="true" class="quarto-color-scheme-extra" id="quarto-bootstrap" data-mode="light">
<script id="quarto-search-options" type="application/json">{
  "location": "navbar",
  "copy-button": false,
  "collapse-after": 3,
  "panel-placement": "end",
  "type": "textbox",
  "limit": 50,
  "keyboard-shortcut": [
    "f",
    "/",
    "s"
  ],
  "language": {
    "search-no-results-text": "No results",
    "search-matching-documents-text": "matching documents",
    "search-copy-link-title": "Copy link to search",
    "search-hide-matches-text": "Hide additional matches",
    "search-more-match-text": "more match in this document",
    "search-more-matches-text": "more matches in this document",
    "search-clear-button-title": "Clear",
    "search-text-placeholder": "",
    "search-detached-cancel-button-title": "Cancel",
    "search-submit-button-title": "Submit",
    "search-label": "Search"
  }
}</script>


<meta property="og:title" content="The cost of O’Neil habitation – Yuxi on the Wired">
<meta property="og:description" content="To win (?) a twitter argument, we calculated the energetic cost of O’Neil habitat per person. Oddly, it is just affordable by modern standards, ~0.72 million USD per person. Let it be known that the SF housing crisis is cheaper to solve by building O’Neil cylinders.">
<meta property="og:image" content="https://yuxi.ml/logs/posts/2025-oneil-cylinder/figure/O'Neil%20cylinder.png">
<meta property="og:site_name" content="Yuxi on the Wired">
<meta name="twitter:title" content="The cost of O’Neil habitation – Yuxi on the Wired">
<meta name="twitter:description" content="To win (?) a twitter argument, we calculated the energetic cost of O’Neil habitat per person. Oddly, it is just affordable by modern standards, ~0.72 million USD per person. Let it be known that the SF housing crisis is cheaper to solve by building O’Neil cylinders.">
<meta name="twitter:image" content="https://yuxi.ml/logs/posts/2025-oneil-cylinder/figure/O'Neil%20cylinder.png">
<meta name="twitter:card" content="summary_large_image">
</head>

<body class="floating nav-fixed slimcontent quarto-light"><script id="quarto-html-before-body" type="application/javascript">
    const toggleBodyColorMode = (bsSheetEl) => {
      const mode = bsSheetEl.getAttribute("data-mode");
      const bodyEl = window.document.querySelector("body");
      if (mode === "dark") {
        bodyEl.classList.add("quarto-dark");
        bodyEl.classList.remove("quarto-light");
      } else {
        bodyEl.classList.add("quarto-light");
        bodyEl.classList.remove("quarto-dark");
      }
    }
    const toggleBodyColorPrimary = () => {
      const bsSheetEl = window.document.querySelector("link#quarto-bootstrap:not([rel=disabled-stylesheet])");
      if (bsSheetEl) {
        toggleBodyColorMode(bsSheetEl);
      }
    }
    const setColorSchemeToggle = (alternate) => {
      const toggles = window.document.querySelectorAll('.quarto-color-scheme-toggle');
      for (let i=0; i < toggles.length; i++) {
        const toggle = toggles[i];
        if (toggle) {
          if (alternate) {
            toggle.classList.add("alternate");
          } else {
            toggle.classList.remove("alternate");
          }
        }
      }
    };
    const toggleColorMode = (alternate) => {
      // Switch the stylesheets
      const primaryStylesheets = window.document.querySelectorAll('link.quarto-color-scheme:not(.quarto-color-alternate)');
      const alternateStylesheets = window.document.querySelectorAll('link.quarto-color-scheme.quarto-color-alternate');
      manageTransitions('#quarto-margin-sidebar .nav-link', false);
      if (alternate) {
        // note: dark is layered on light, we don't disable primary!
        enableStylesheet(alternateStylesheets);
        for (const sheetNode of alternateStylesheets) {
          if (sheetNode.id === "quarto-bootstrap") {
            toggleBodyColorMode(sheetNode);
          }
        }
      } else {
        disableStylesheet(alternateStylesheets);
        enableStylesheet(primaryStylesheets)
        toggleBodyColorPrimary();
      }
      manageTransitions('#quarto-margin-sidebar .nav-link', true);
      // Switch the toggles
      setColorSchemeToggle(alternate)
      // Hack to workaround the fact that safari doesn't
      // properly recolor the scrollbar when toggling (#1455)
      if (navigator.userAgent.indexOf('Safari') > 0 && navigator.userAgent.indexOf('Chrome') == -1) {
        manageTransitions("body", false);
        window.scrollTo(0, 1);
        setTimeout(() => {
          window.scrollTo(0, 0);
          manageTransitions("body", true);
        }, 40);
      }
    }
    const disableStylesheet = (stylesheets) => {
      for (let i=0; i < stylesheets.length; i++) {
        const stylesheet = stylesheets[i];
        stylesheet.rel = 'disabled-stylesheet';
      }
    }
    const enableStylesheet = (stylesheets) => {
      for (let i=0; i < stylesheets.length; i++) {
        const stylesheet = stylesheets[i];
        if(stylesheet.rel !== 'stylesheet') { // for Chrome, which will still FOUC without this check
          stylesheet.rel = 'stylesheet';
        }
      }
    }
    const manageTransitions = (selector, allowTransitions) => {
      const els = window.document.querySelectorAll(selector);
      for (let i=0; i < els.length; i++) {
        const el = els[i];
        if (allowTransitions) {
          el.classList.remove('notransition');
        } else {
          el.classList.add('notransition');
        }
      }
    }
    const isFileUrl = () => {
      return window.location.protocol === 'file:';
    }
    const hasAlternateSentinel = () => {
      let styleSentinel = getColorSchemeSentinel();
      if (styleSentinel !== null) {
        return styleSentinel === "alternate";
      } else {
        return false;
      }
    }
    const setStyleSentinel = (alternate) => {
      const value = alternate ? "alternate" : "default";
      if (!isFileUrl()) {
        window.localStorage.setItem("quarto-color-scheme", value);
      } else {
        localAlternateSentinel = value;
      }
    }
    const getColorSchemeSentinel = () => {
      if (!isFileUrl()) {
        const storageValue = window.localStorage.getItem("quarto-color-scheme");
        return storageValue != null ? storageValue : localAlternateSentinel;
      } else {
        return localAlternateSentinel;
      }
    }
    const toggleGiscusIfUsed = (isAlternate, darkModeDefault) => {
      const baseTheme = document.querySelector('#giscus-base-theme')?.value ?? 'light';
      const alternateTheme = document.querySelector('#giscus-alt-theme')?.value ?? 'dark';
      let newTheme = '';
      if(authorPrefersDark) {
        newTheme = isAlternate ? baseTheme : alternateTheme;
      } else {
        newTheme = isAlternate ? alternateTheme : baseTheme;
      }
      const changeGiscusTheme = () => {
        // From: https://github.com/giscus/giscus/issues/336
        const sendMessage = (message) => {
          const iframe = document.querySelector('iframe.giscus-frame');
          if (!iframe) return;
          iframe.contentWindow.postMessage({ giscus: message }, 'https://giscus.app');
        }
        sendMessage({
          setConfig: {
            theme: newTheme
          }
        });
      }
      const isGiscussLoaded = window.document.querySelector('iframe.giscus-frame') !== null;
      if (isGiscussLoaded) {
        changeGiscusTheme();
      }
    };
    const authorPrefersDark = false;
    const darkModeDefault = authorPrefersDark;
      document.querySelector('link#quarto-text-highlighting-styles.quarto-color-scheme-extra').rel = 'disabled-stylesheet';
      document.querySelector('link#quarto-bootstrap.quarto-color-scheme-extra').rel = 'disabled-stylesheet';
    let localAlternateSentinel = darkModeDefault ? 'alternate' : 'default';
    // Dark / light mode switch
    window.quartoToggleColorScheme = () => {
      // Read the current dark / light value
      let toAlternate = !hasAlternateSentinel();
      toggleColorMode(toAlternate);
      setStyleSentinel(toAlternate);
      toggleGiscusIfUsed(toAlternate, darkModeDefault);
      window.dispatchEvent(new Event('resize'));
    };
    // Switch to dark mode if need be
    if (hasAlternateSentinel()) {
      toggleColorMode(true);
    } else {
      toggleColorMode(false);
    }
  </script>

<div id="quarto-search-results"></div>
  <header id="quarto-header" class="headroom fixed-top quarto-banner">
    <nav class="navbar navbar-expand-lg " data-bs-theme="dark">
      <div class="navbar-container container-fluid">
      <div class="navbar-brand-container mx-auto">
    <a href="../../../index.html" class="navbar-brand navbar-brand-logo">
    <img src="../../../img/favicon.ico" alt="" class="navbar-logo">
    </a>
    <a class="navbar-brand" href="../../../index.html">
    <span class="navbar-title">Yuxi on the Wired</span>
    </a>
  </div>
            <div id="quarto-search" class="" title="Search"></div>
          <button class="navbar-toggler" type="button" data-bs-toggle="collapse" data-bs-target="#navbarCollapse" aria-controls="navbarCollapse" role="menu" aria-expanded="false" aria-label="Toggle navigation" onclick="if (window.quartoToggleHeadroom) { window.quartoToggleHeadroom(); }">
  <span class="navbar-toggler-icon"></span>
</button>
          <div class="collapse navbar-collapse" id="navbarCollapse">
            <ul class="navbar-nav navbar-nav-scroll me-auto">
  <li class="nav-item">
    <a class="nav-link" href="../../../essays/index.html"> 
<span class="menu-text">Essays</span></a>
  </li>  
  <li class="nav-item">
    <a class="nav-link" href="../../../sketches/index.html"> 
<span class="menu-text">Sketches</span></a>
  </li>  
  <li class="nav-item">
    <a class="nav-link" href="../../../logs/index.html"> 
<span class="menu-text">Logs</span></a>
  </li>  
  <li class="nav-item">
    <a class="nav-link" href="../../../notes/index.html"> 
<span class="menu-text">Notes</span></a>
  </li>  
  <li class="nav-item">
    <a class="nav-link" href="../../../docs/index.html"> 
<span class="menu-text">Docs</span></a>
  </li>  
  <li class="nav-item">
    <a class="nav-link" href="../../../projects/index.html"> 
<span class="menu-text">Projects</span></a>
  </li>  
  <li class="nav-item">
    <a class="nav-link" href="../../../about/index.html"> 
<span class="menu-text">About</span></a>
  </li>  
</ul>
            <ul class="navbar-nav navbar-nav-scroll ms-auto">
  <li class="nav-item compact">
    <a class="nav-link" href="mailto:yuxi_liu@berkeley.com"> <i class="bi bi-envelope" role="img" aria-label="email">
</i> 
<span class="menu-text"></span></a>
  </li>  
  <li class="nav-item compact">
    <a class="nav-link" href="../../../feeds.xml"> <i class="bi bi-rss" role="img">
</i> 
<span class="menu-text"></span></a>
  </li>  
</ul>
          </div> <!-- /navcollapse -->
            <div class="quarto-navbar-tools">
  <a href="" class="quarto-color-scheme-toggle quarto-navigation-tool  px-1" onclick="window.quartoToggleColorScheme(); return false;" title="Toggle dark mode"><i class="bi"></i></a>
</div>
      </div> <!-- /container-fluid -->
    </nav>
</header>
<!-- content -->
<header id="title-block-header" class="quarto-title-block default toc-left page-columns page-full">
  <div class="quarto-title-banner page-columns page-full">
    <div class="quarto-title column-body">
      <div class="quarto-title-block"><div><h1 class="title">The cost of O’Neil habitation</h1><button type="button" class="btn code-tools-button" id="quarto-code-tools-source"><i class="bi"></i> Code</button></div></div>
                  <div>
        <div class="description">
          To win (?) a twitter argument, we calculated the energetic cost of O’Neil habitat per person. Oddly, it is just affordable by modern standards, ~0.72 million USD per person. Let it be known that the SF housing crisis is cheaper to solve by building O’Neil cylinders.
        </div>
      </div>
                          <div class="quarto-categories">
                <div class="quarto-category">fun</div>
                <div class="quarto-category">scifi</div>
                <div class="quarto-category">economics</div>
              </div>
                  </div>
  </div>
    
  
  <div class="quarto-title-meta">

      <div>
      <div class="quarto-title-meta-heading">Author</div>
      <div class="quarto-title-meta-contents">
               <p>Yuxi Liu </p>
            </div>
    </div>
      
      <div>
      <div class="quarto-title-meta-heading">Published</div>
      <div class="quarto-title-meta-contents">
        <p class="date">April 18, 2025</p>
      </div>
    </div>
    
      <div>
      <div class="quarto-title-meta-heading">Modified</div>
      <div class="quarto-title-meta-contents">
        <p class="date-modified">April 18, 2025</p>
      </div>
    </div>
      
    </div>
    
  
  </header><div id="quarto-content" class="quarto-container page-columns page-rows-contents page-layout-article page-navbar">
<!-- sidebar -->
  <nav id="quarto-sidebar" class="sidebar collapse collapse-horizontal quarto-sidebar-collapse-item sidebar-navigation floating overflow-auto">
    <nav id="TOC" role="doc-toc" class="toc-active">
    <h2 id="toc-title">On this page</h2>
   
  <ul>
  <li><a href="#how-expensive-is-a-standard-oneil-cylinder" id="toc-how-expensive-is-a-standard-oneil-cylinder" class="nav-link active" data-scroll-target="#how-expensive-is-a-standard-oneil-cylinder">How expensive is a standard O’Neil cylinder?</a>
  <ul class="collapse">
  <li><a href="#why-bother" id="toc-why-bother" class="nav-link" data-scroll-target="#why-bother">Why bother?</a></li>
  <li><a href="#mass-cost" id="toc-mass-cost" class="nav-link" data-scroll-target="#mass-cost">Mass cost</a></li>
  <li><a href="#launch-cost" id="toc-launch-cost" class="nav-link" data-scroll-target="#launch-cost">Launch cost</a></li>
  <li><a href="#upkeep-cost" id="toc-upkeep-cost" class="nav-link" data-scroll-target="#upkeep-cost">Upkeep cost</a></li>
  </ul></li>
  <li><a href="#is-image-segmentation-with-gemini-2.5-worth-it" id="toc-is-image-segmentation-with-gemini-2.5-worth-it" class="nav-link" data-scroll-target="#is-image-segmentation-with-gemini-2.5-worth-it">Is image segmentation with Gemini 2.5 worth it?</a></li>
  
  </ul>
</nav>
</nav>
<div id="quarto-sidebar-glass" class="quarto-sidebar-collapse-item" data-bs-toggle="collapse" data-bs-target=".quarto-sidebar-collapse-item"></div>
<!-- margin-sidebar -->
    <div id="quarto-margin-sidebar" class="sidebar margin-sidebar zindex-bottom">
    </div>
<!-- main -->
<main class="content quarto-banner-title-block page-columns page-full" id="quarto-document-content">






<section id="how-expensive-is-a-standard-oneil-cylinder" class="level2 page-columns page-full">
<h2 class="anchored" data-anchor-id="how-expensive-is-a-standard-oneil-cylinder">How expensive is a standard O’Neil cylinder?</h2>
<p>Assuming standard golden-age sci-fi technology, the marginal cost per person on an O’Neil cylinder should be about 24 TJ, just to get all the raw material off the moon/asteroid and into orbit. The cost is 25× if launching from earth. The construction costs are unknown, but should be less than that.</p>
<table class="caption-top table">
<thead>
<tr class="header">
<th>item</th>
<th>mass/ton</th>
<th>cost / TJ</th>
<th></th>
</tr>
</thead>
<tbody>
<tr class="odd">
<td>farm with vineyard</td>
<td>2000</td>
<td>20</td>
<td></td>
</tr>
<tr class="even">
<td>suburb house with yard and white picket fence</td>
<td>160</td>
<td>1.6</td>
<td></td>
</tr>
<tr class="odd">
<td>standard parkland (per person)</td>
<td>250</td>
<td>2.5</td>
<td></td>
</tr>
</tbody>
</table>
<p>Modern humans consume about 10 kW per person, so the cost of getting everything into orbit is about equal to 72 years of power consumption. This makes it just about affordable by modern economic standards. Assuming modern electricity price, it would cost about $0.72M, which is half the median price of listed houses in San Francisco (<a href="https://www.redfin.com/city/17151/CA/San-Francisco/housing-market">Source</a>).</p>
<div class="quarto-figure quarto-figure-center page-columns page-full">
<figure class="figure page-columns page-full">
<p><img src="figure/O'Neil cylinder.png" class="img-fluid figure-img"></p>
<figcaption class="margin-caption">The O’Neil cylinder art used as reference.</figcaption>
</figure>
</div>
<p>Talked over with <a href="https://chatgpt.com/share/6802d4a2-7f08-800a-8545-7c2de08e4b21">GPT o3</a>.</p>
<section id="why-bother" class="level3">
<h3 class="anchored" data-anchor-id="why-bother">Why bother?</h3>
<p>Because <a href="https://xkcd.com/386/">someone might be wrong on the Internet</a>!</p>
<blockquote class="twitter-tweet blockquote">
<p lang="en" dir="ltr">
this is me: <a href="https://t.co/2PTP1LpJ4d">https://t.co/2PTP1LpJ4d</a>
</p>
— croissanthology (@croissanthology) <a href="https://twitter.com/croissanthology/status/1913216595993776186?ref_src=twsrc%5Etfw">April 18, 2025</a>
</blockquote>
<script async="" src="https://platform.twitter.com/widgets.js" charset="utf-8"></script>
<p>your desires are out of date<br>
click &gt;&gt;HERE&lt;&lt; to hypernovate</p>
<blockquote class="twitter-tweet blockquote">
<p lang="en" dir="ltr">
I'm sorry, but this is just the most asinine thing imaginable, I mean just look at that, pure 70s suburbanite boomer logic scaled way beyond its paygrade <a href="https://t.co/xahab9pHXO">pic.twitter.com/xahab9pHXO</a>
</p>
— Yuxi on the Wired (@layer07_yuxi) <a href="https://twitter.com/layer07_yuxi/status/1913348670445203579?ref_src=twsrc%5Etfw">April 18, 2025</a>
</blockquote>
<script async="" src="https://platform.twitter.com/widgets.js" charset="utf-8"></script>
</section>
<section id="mass-cost" class="level3">
<h3 class="anchored" data-anchor-id="mass-cost">Mass cost</h3>
<p>The general rule: 1 m² of land or 1-person building, requires ~1 m of depth and ~1 ton of mass. Water has density ~1 ton/m³, and loose dry soil has density ~1.3 ton/m³. This general rule is correct within a factor of 10 under most variations. For growing plants and crops, the mass ratio of soil to water is about 5 to 1.</p>
<p>The farmland to support a person is between 0.5 to 2 acres depending on the specific diet. (<a href="https://news.cornell.edu/stories/2007/10/diet-little-meat-more-efficient-many-vegetarian-diets">Source</a>) The hypothetical suburban solarpunk probably wants to stick to the vegetarian + diary diet and work with their own two hands, so 0.5 acres = 2000 m² should be enough.</p>
<p>As for the vineyard, the French consumes <a href="https://ourworldindata.org/grapher/wine-consumption-per-capita">6 liters of wine a year</a>, which requires about 20 kg of grapes. Vineyard can produce about 1 to 3 ton/acre (<a href="https://www.enologyinternational.com/yield9.php">Source</a>), so that gives about 40 m², which is negligible. There should be plenty of room for the extras. Together, let’s say it would take 2200 m² of farmland.</p>
<p>The typical root depth for most crops is ~0.6 m, giving 1300 m³ of soil, or 2000 ton.</p>
<p>The standard parkland in American cities averages to about 1 acre per 100 people, or about 40 m² per person. (<a href="https://www.nrpa.org/about-national-recreation-and-park-association/press-room/new-report-shows-the-typical-park-and-rec-agency-has-one-park-for-every-2181-residents/">Source</a>) Most of the park can be grassland, so we assume 0.3 m of depth.</p>
<p>It is unclear how much of the parkland area is portioned for water. Looking at a satellite map of the NYC central park, it seems like ¼. The artificial lake should be about 10 m deep (the depth of the <a href="https://en.wikipedia.org/wiki/Jacqueline_Kennedy_Onassis_Reservoir">NYC central park’s lake</a>), but that is quite expensive. So, about 100 m³ of soil and 100 m³ of water, giving about 250 ton.</p>
<p>To build the classic suburban house with a small grassland and white picket fence <del>and 2.5 kids</del>, we need two parts: the ground and the house.</p>
<p>The ground just needs to support grass, so again 0.3 m deep. US Census shows single‑family lots of 0.32&nbsp;ac (≈1&nbsp;300&nbsp;m²) for 1970‑era builds (<a href="https://www.census.gov/content/dam/Census/programs-surveys/ahs/working-papers/Housing-by-Year-Built.pdf#page=3">Source</a>). That gives 400 m³ = 500 ton of soil. The water in the soil would be about 100 ton.</p>
<p>A standard house on earth needs a deeper foundation, but they don’t need that on an O’Neil cylinder, since it can be directly supported on the “bedrock” below. As for the mass of the house itself, according to <a href="https://doi.org/10.1029/2022EF003465">“The Weight of New York City” (2023)</a>, the mass of the built environment in New York City is about 1 ton/m². So taking that as the cost of housing per person, including the concrete, the steel, etc, we estimate the housing cost is about 200 ton.</p>
<p>So the 1970s suburb house costs about 800 ton, for a family of 5, or 160 ton/person.</p>
</section>
<section id="launch-cost" class="level3">
<h3 class="anchored" data-anchor-id="launch-cost">Launch cost</h3>
<p>The prompt:</p>
<blockquote class="blockquote">
<p>Something that would make sense in a hard golden age sci-fi. Something in which an ONeil cylinder might feature without being out of place. Not too weak but not too strong either, since either way, the ONeil cylinder would be out of place, much like it would be out of place for a horserider to deliver a flashdrive.</p>
</blockquote>
<p>The cost of launching mass into space varies. The most expensive method is to launch from earth using chemical rockets. The main cost are two: paying the gravitational energy (63 MJ/kg), and the wasted energy in accelerating the rocket and the fuel. Using some kind of pure launch system (such as a coil gun or a space elevator) would come close to eliminating the second kind of waste.</p>
<p>Mining from moon would decrease the first kind (The escape velocity of moon is 1/5 that of earth, so the energy saving is ~25×, to just 3 MJ/kg). Mining from asteroids would mostly eliminate the first kind.</p>
<p>GPT o3 suggested that the cost of pure-launch from the moon is about 7 MJ/kg, which seems kind of accurate? Feels too optimistic to only cost 2× that of the bare minimum. Rounding it up to 10 MJ/kg.</p>
</section>
<section id="upkeep-cost" class="level3">
<h3 class="anchored" data-anchor-id="upkeep-cost">Upkeep cost</h3>
<p>Apparently <em>after</em> launching all that stuff into orbit, the upkeep for all that stuff is not more expensive than on earth, assuming that the structural components holding the cylinder together and the air inside from leaking don’t cost much energy to maintain. Carbon-glass fibers are okay. Rocket engines constantly pushing the hull inwards are not. Purpose-engineered organisms with infused self-healing biomineral bones and sinews… possibly?</p>
<p>So that would be about 10 kW/person, the average power consumption per Canadian human in 2023. (<a href="https://ourworldindata.org/grapher/per-capita-energy-use">Source</a>)</p>
</section>
</section>
<section id="is-image-segmentation-with-gemini-2.5-worth-it" class="level2">
<h2 class="anchored" data-anchor-id="is-image-segmentation-with-gemini-2.5-worth-it">Is image segmentation with Gemini 2.5 worth it?</h2>
<p><a href="https://simonwillison.net/2025/Apr/18/gemini-image-segmentation/">Simon Willison reports</a> that Gemini 2.5 can return image segmentation masks as base64 encoded PNGs embedded in JSON strings, and estimated that the cheapest option is by Gemini 2.5 Flash non-thinking. Specifically, for a photo of resolution 1000×1000, with 2 non-overlapping objects (2 pelicans in flight), masking and boxing cost 303 input tokens and 123 output tokens, for a price of $1e-4/image.</p>
<p>How good is it compared to standard SOTA methods, like SAM and YOLO?</p>
<p>The SAM 2 series of models take 0.01 to 0.03 seconds per image (<a href="https://github.com/facebookresearch/sam2?tab=readme-ov-file#sam-2-checkpoints">Source</a>) on an Nvidia A100 as of 2024. Current price of A100 rental is about $1.5/hr, so the cost is $4e-6 to $1e-5/image in batch mode.</p>
<p>As for YOLO, the YOLOv8x achieved 280 frames per second on A100, (<a href="https://arxiv.org/pdf/2406.10139v1">Source</a>) so that costs about $1.5e-6/image.</p>
<p>How about latency? YOLO and SAM are both locally hostable, but Gemini is only available across an API call. The throughput is about 1 second per 100 tokens, while the latency (time until first token) is about 10 seconds, so let’s call it 1–10 seconds. (<a href="https://artificialanalysis.ai/models/gemini-2-5-flash">Source</a>)</p>
<table class="caption-top table">
<caption>Summary table for the cost and latency of various object boxing and masking systems.</caption>
<thead>
<tr class="header">
<th>model</th>
<th>latency (ms)</th>
<th>cost per million image (USD)</th>
</tr>
</thead>
<tbody>
<tr class="odd">
<td><code>YOLOv8x</code></td>
<td>4</td>
<td>1.5</td>
</tr>
<tr class="even">
<td><code>sam2_hiera_tiny</code></td>
<td>10</td>
<td>4</td>
</tr>
<tr class="odd">
<td><code>sam2_hiera_large</code></td>
<td>30</td>
<td>10</td>
</tr>
<tr class="even">
<td><code>Gemini 2.5 Flash</code> (nonthinking)</td>
<td>1000–10000</td>
<td>100</td>
</tr>
</tbody>
</table>
<p>Well, it’s certainly not good for any large-batch processing, but pretty impressive that it is within a factor of 10 compared to <code>sam2_hiera_large</code>.</p>
</section>


<div id="quarto-appendix" class="default"><section id="appendix-the-tweet-thread" class="level2 appendix"><h2 class="anchored quarto-appendix-heading">Appendix: the tweet thread</h2><div class="quarto-appendix-contents">

<section id="thread-1" class="level3">
<h3 class="anchored" data-anchor-id="thread-1">Thread 1</h3>
<p>(<a href="https://x.com/croissanthology/status/1910846754657890798">Source</a>)</p>
<p><strong>niplav</strong>&nbsp;<code>@niplav_site</code> —&nbsp;Apr&nbsp;11<br>
&gt; likely<br>
&gt;<br>
&gt; (I’m very in favor of doing the efficient thing)<br>
&gt;<br>
&gt; I suspect it entails not dyson swarms but disassembling the stars and/or forging them into black holes, maybe aestivating</p>
<p><strong>croissanthology</strong>&nbsp;<code>@croissanthology</code> —&nbsp;Apr&nbsp;11<br>
&gt; yeah definitely not dyson swarms either, I just think they also happen to be cuter than shkadov thrusters</p>
<p><strong>niplav</strong>&nbsp;<code>@niplav_site</code> —&nbsp;Apr&nbsp;11<br>
&gt; hm<br>
&gt;<br>
&gt; cuteness: dyson swarms&gt;shkadov thrusters&gt;criswell star lifting<br>
&gt; awesomeness: shkadov thrusters&gt;criswell star lifting&gt;dyson swarms<br>
&gt; terror: criswell star lifting&gt;shkadov thrusters&gt;dyson swarms</p>
<p><strong>croissanthology</strong>&nbsp;<code>@croissanthology</code> —&nbsp;5:05&nbsp;PM&nbsp;·&nbsp;Apr&nbsp;11&nbsp;·&nbsp;186&nbsp;Views<br>
&gt; I’m sorry, but this is just the most asinine thing imaginable, I mean just look at that, pure caveman logic scaled way beyond its paygrade</p>
<p>[Image of a Shkadov thruster]</p>
<p><strong>croissanthology</strong>&nbsp;<code>@croissanthology</code> —&nbsp;Apr&nbsp;11<br>
&gt; groo want shiny round thing move, groo redirect surface radiation of thing with giant mirror, groo satisfied, groo wait, groo patient, groo worried embers of shiny round thing go out, but groo patient</p>
<p><strong>croissanthology</strong>&nbsp;<code>@croissanthology</code> —&nbsp;Apr&nbsp;11<br>
&gt; it grow dark for groo. groo patient. groo faithful. groo still hopes. another day come for groo. groo hopes.</p>
<p><strong>niplav</strong>&nbsp;<code>@niplav_site</code> —&nbsp;Apr&nbsp;11<br>
&gt; yes, it’s great :-D<br>
&gt;<br>
&gt; “I am launching a star in your general direction. Pray I don’t launch more.”<br>
&gt;<br>
&gt; it’s so barbaric I love it</p>
<p><strong>croissanthology</strong>&nbsp;<code>@croissanthology</code> —&nbsp;Apr&nbsp;11<br>
&gt; thag look with worry at shiny round thing coming his way. groo patient. thag worried. shiny round thing slow. thag laugh. thag go on with life. this seem like problem for great-grand-thag.</p>
<p><strong>Manic&nbsp;Pixie&nbsp;AGI</strong>&nbsp;<code>@manic_pixie_agi</code> —&nbsp;Apr&nbsp;12<br>
&gt; <em>great grand thag reporients the device back at great grand groo</em><br>
&gt; “A problem for great great great grand groo”</p>
</section>
<section id="thread-2" class="level3">
<h3 class="anchored" data-anchor-id="thread-2">Thread 2</h3>
<p>(<a href="https://x.com/layer07_yuxi/status/1913358799844655152">Source</a>)</p>
<p><strong>near</strong>&nbsp;<code>@nearcyan</code> —&nbsp;Apr&nbsp;16<br>
&gt; seems kinda clear we are definitely getting the ‘software singularity’ far, far before the ‘hardware singularity’, which seems.. more delayed than ever<br>
&gt;<br>
&gt; and paul christiano-esque takes seem to have panned out very well<br>
&gt;<br>
&gt; so, kinda full cyberpunk timeline? almost too predictable?</p>
<p><strong>imit</strong>&nbsp;<code>@imitationlearn</code> —&nbsp;Apr&nbsp;17<br>
&gt; how is this cyberpunk? cyberpunk seems like it requires quite a bit of hardware dev to me</p>
<p><strong>croissanthology</strong>&nbsp;<code>@croissanthology</code> —&nbsp;Apr&nbsp;17<br>
&gt; I’d call a reality where everything is the same as now but we’re all wearing VR / ghibligoggles all the time cyberpunk, despite that being almost entirely software.<br>
&gt;<br>
&gt; Similarly, when I walk past parks in french suburbia and half the people are sitting or standing in the shade watching tik tokk, that feels very cyberpunk to me</p>
<p><strong>Yuxi on the Wired</strong>&nbsp;<code>@layer07_yuxi</code> —&nbsp;19h<br>
&gt; eh that seems way too utopian to be cyberpunk</p>
<p><strong>croissanthology</strong>&nbsp;<code>@croissanthology</code> —&nbsp;14h<br>
&gt; I think I’m a lot more narrowly anthropic/humanist than people in my simcluster. Glued to VR is one of the hopeful timelines but still it manages to disgust me, and so seemed suitably cyberpunk.<br>
&gt;<br>
&gt; to be clear my circle under “humanist” comprises LLMs and whatever it is Yuxi is. Maybe it’s from being fed endless classic futurism as a kid, but my brain can’t manage to extrapolate a better future than<br>
&gt;<br>
&gt; “solarpunk animism shire galaxy harvesting o’neill cylinder sit under his own vine greener grass transhumanism”<br>
&gt;<br>
&gt; very primal and hunter gathery of me, I admit. But anyway my dystopian tolerance is pretty low, as my environment measures such things.</p>
<p><strong>Yuxi on the Wired</strong>&nbsp;<code>@layer07_yuxi</code><br>
&gt; I’m sorry, but this is just the most asinine thing imaginable, I mean just look at that, pure 70s suburbanite boomer logic scaled way beyond its paygrade</p>
<p>[Image of that O’Neil cylinder]</p>
<p><strong>croissanthology</strong>&nbsp;<code>@croissanthology</code> —&nbsp;5h<br>
&gt; yeah tbc I do know these are inefficient as hell and everything that lives will end up running on a ~chip, and the O’Neill cylinders were just generally gesturing in the direction my brain currently thinks of as “utopia”</p>
<p><strong>Yuxi on the Wired</strong>&nbsp;<code>@layer07_yuxi</code> —&nbsp;5h<br>
&gt; Yes, we understand. We have desires too that are too inefficient to exist and will be burnt away in the coming Singularity like morning dew.<br>
&gt; In Bostrom’s words, these desires are “astronomical waste”.<br>
&gt; But just for the record, here is what we understand as cyberpunk:</p>
<p>[Screenshot of <a href="http://www.ccru.net/swarm1/1_melt.htm"><em>Meltdown</em></a> going from “[[ ]] Meltdown has a place for you” to “untouched by human feeling.”. ]</p>
<p><strong>norvid_studies</strong>&nbsp;<code>@norvid_studies</code> —&nbsp;4h<br>
&gt; i think that’s pretty much the exact opposite of what bostrom meant by the term lol. not that terminological repurposing isn’t the birthright of every free twittizen</p>
<p><strong>Yuxi on the Wired</strong>&nbsp;<code>@layer07_yuxi</code> —&nbsp;4h<br>
&gt; Exact opposite? This is clearly just standard Bostromian astronomical waste: Building O’Neil cylinders to house like 1 million slow beings, when all that energy could have been used to power a micro-sector of a Dyson swarm containing 1 trillion trillion fast beings?</p>
<p><strong>norvid_studies</strong>&nbsp;<code>@norvid_studies</code> —&nbsp;4h<br>
&gt; if the successor entities have the same desires just run much faster and denser, then yes the bioform version is astronomical waste in the bostrom sense– you’re leaving fat juicy qualia on the table</p>
<p><strong>norvid_studies</strong>&nbsp;<code>@norvid_studies</code> —&nbsp;4h<br>
&gt; if they don’t and it’s more of a ‘disneyland with no children scenario’ then<br>
&gt;<br>
&gt; the so-called waste being competed out of existence is the original desired thing we were bemoaning was being wasted by the dead empty cosmos in the first place; in which scenario it would be “the opposite” of what he meant there.</p>


<!-- -->

</section>
</div></section></div></main> <!-- /main -->
<!-- file: html/copy‑anchors-js.html -->

<script type="module">

document.addEventListener("DOMContentLoaded", () => {

  // 1. All little ¶ icons Quarto/AnchorJS adds

  document.querySelectorAll("a.anchorjs-link").forEach(anchor => {

    anchor.addEventListener("click", async (evt) => {

      // Keep normal scroll behaviour but stop full page reload

      evt.preventDefault();



      // Build absolute URL: origin + path + #hash

      const url = `${location.origin}${location.pathname}${anchor.getAttribute("href")}`;



      // 2. Try modern Clipboard API first

      try {

        await navigator.clipboard.writeText(url);

      } catch {

        // 3. Fallback for legacy browsers

        const helper = Object.assign(document.createElement("input"), { value: url });

        document.body.appendChild(helper);

        helper.select();

        document.execCommand("copy");

        helper.remove();

      }

      // TODO: The following two doesn't work yet

      // 4. Brief visual confirmation (optional)

      anchor.dataset.tooltip = "Copied!";

      setTimeout(() => delete anchor.dataset.tooltip, 1500);



      // 5. Still jump to the heading

      history.pushState(null, "", anchor.getAttribute("href"));

    }, false);

  });

});

</script>

<script id="quarto-html-after-body" type="application/javascript">
  window.document.addEventListener("DOMContentLoaded", function (event) {
    // Ensure there is a toggle, if there isn't float one in the top right
    if (window.document.querySelector('.quarto-color-scheme-toggle') === null) {
      const a = window.document.createElement('a');
      a.classList.add('top-right');
      a.classList.add('quarto-color-scheme-toggle');
      a.href = "";
      a.onclick = function() { try { window.quartoToggleColorScheme(); } catch {} return false; };
      const i = window.document.createElement("i");
      i.classList.add('bi');
      a.appendChild(i);
      window.document.body.appendChild(a);
    }
    setColorSchemeToggle(hasAlternateSentinel())
    const icon = "";
    const anchorJS = new window.AnchorJS();
    anchorJS.options = {
      placement: 'right',
      icon: icon
    };
    anchorJS.add('.anchored');
    const isCodeAnnotation = (el) => {
      for (const clz of el.classList) {
        if (clz.startsWith('code-annotation-')) {                     
          return true;
        }
      }
      return false;
    }
    const onCopySuccess = function(e) {
      // button target
      const button = e.trigger;
      // don't keep focus
      button.blur();
      // flash "checked"
      button.classList.add('code-copy-button-checked');
      var currentTitle = button.getAttribute("title");
      button.setAttribute("title", "Copied!");
      let tooltip;
      if (window.bootstrap) {
        button.setAttribute("data-bs-toggle", "tooltip");
        button.setAttribute("data-bs-placement", "left");
        button.setAttribute("data-bs-title", "Copied!");
        tooltip = new bootstrap.Tooltip(button, 
          { trigger: "manual", 
            customClass: "code-copy-button-tooltip",
            offset: [0, -8]});
        tooltip.show();    
      }
      setTimeout(function() {
        if (tooltip) {
          tooltip.hide();
          button.removeAttribute("data-bs-title");
          button.removeAttribute("data-bs-toggle");
          button.removeAttribute("data-bs-placement");
        }
        button.setAttribute("title", currentTitle);
        button.classList.remove('code-copy-button-checked');
      }, 1000);
      // clear code selection
      e.clearSelection();
    }
    const getTextToCopy = function(trigger) {
        const codeEl = trigger.previousElementSibling.cloneNode(true);
        for (const childEl of codeEl.children) {
          if (isCodeAnnotation(childEl)) {
            childEl.remove();
          }
        }
        return codeEl.innerText;
    }
    const clipboard = new window.ClipboardJS('.code-copy-button:not([data-in-quarto-modal])', {
      text: getTextToCopy
    });
    clipboard.on('success', onCopySuccess);
    if (window.document.getElementById('quarto-embedded-source-code-modal')) {
      const clipboardModal = new window.ClipboardJS('.code-copy-button[data-in-quarto-modal]', {
        text: getTextToCopy,
        container: window.document.getElementById('quarto-embedded-source-code-modal')
      });
      clipboardModal.on('success', onCopySuccess);
    }
    const viewSource = window.document.getElementById('quarto-view-source') ||
                       window.document.getElementById('quarto-code-tools-source');
    if (viewSource) {
      const sourceUrl = viewSource.getAttribute("data-quarto-source-url");
      viewSource.addEventListener("click", function(e) {
        if (sourceUrl) {
          // rstudio viewer pane
          if (/\bcapabilities=\b/.test(window.location)) {
            window.open(sourceUrl);
          } else {
            window.location.href = sourceUrl;
          }
        } else {
          const modal = new bootstrap.Modal(document.getElementById('quarto-embedded-source-code-modal'));
          modal.show();
        }
        return false;
      });
    }
    function toggleCodeHandler(show) {
      return function(e) {
        const detailsSrc = window.document.querySelectorAll(".cell > details > .sourceCode");
        for (let i=0; i<detailsSrc.length; i++) {
          const details = detailsSrc[i].parentElement;
          if (show) {
            details.open = true;
          } else {
            details.removeAttribute("open");
          }
        }
        const cellCodeDivs = window.document.querySelectorAll(".cell > .sourceCode");
        const fromCls = show ? "hidden" : "unhidden";
        const toCls = show ? "unhidden" : "hidden";
        for (let i=0; i<cellCodeDivs.length; i++) {
          const codeDiv = cellCodeDivs[i];
          if (codeDiv.classList.contains(fromCls)) {
            codeDiv.classList.remove(fromCls);
            codeDiv.classList.add(toCls);
          } 
        }
        return false;
      }
    }
    const hideAllCode = window.document.getElementById("quarto-hide-all-code");
    if (hideAllCode) {
      hideAllCode.addEventListener("click", toggleCodeHandler(false));
    }
    const showAllCode = window.document.getElementById("quarto-show-all-code");
    if (showAllCode) {
      showAllCode.addEventListener("click", toggleCodeHandler(true));
    }
      var localhostRegex = new RegExp(/^(?:http|https):\/\/localhost\:?[0-9]*\//);
      var mailtoRegex = new RegExp(/^mailto:/);
        var filterRegex = new RegExp("https:\/\/yuxi\.ml\/");
      var isInternal = (href) => {
          return filterRegex.test(href) || localhostRegex.test(href) || mailtoRegex.test(href);
      }
      // Inspect non-navigation links and adorn them if external
     var links = window.document.querySelectorAll('a[href]:not(.nav-link):not(.navbar-brand):not(.toc-action):not(.sidebar-link):not(.sidebar-item-toggle):not(.pagination-link):not(.no-external):not([aria-hidden]):not(.dropdown-item):not(.quarto-navigation-tool):not(.about-link)');
      for (var i=0; i<links.length; i++) {
        const link = links[i];
        if (!isInternal(link.href)) {
          // undo the damage that might have been done by quarto-nav.js in the case of
          // links that we want to consider external
          if (link.dataset.originalHref !== undefined) {
            link.href = link.dataset.originalHref;
          }
        }
      }
    function tippyHover(el, contentFn, onTriggerFn, onUntriggerFn) {
      const config = {
        allowHTML: true,
        maxWidth: 500,
        delay: 100,
        arrow: false,
        appendTo: function(el) {
            return el.parentElement;
        },
        interactive: true,
        interactiveBorder: 10,
        theme: 'quarto',
        placement: 'bottom-start',
      };
      if (contentFn) {
        config.content = contentFn;
      }
      if (onTriggerFn) {
        config.onTrigger = onTriggerFn;
      }
      if (onUntriggerFn) {
        config.onUntrigger = onUntriggerFn;
      }
      window.tippy(el, config); 
    }
    const noterefs = window.document.querySelectorAll('a[role="doc-noteref"]');
    for (var i=0; i<noterefs.length; i++) {
      const ref = noterefs[i];
      tippyHover(ref, function() {
        // use id or data attribute instead here
        let href = ref.getAttribute('data-footnote-href') || ref.getAttribute('href');
        try { href = new URL(href).hash; } catch {}
        const id = href.replace(/^#\/?/, "");
        const note = window.document.getElementById(id);
        if (note) {
          return note.innerHTML;
        } else {
          return "";
        }
      });
    }
    const xrefs = window.document.querySelectorAll('a.quarto-xref');
    const processXRef = (id, note) => {
      // Strip column container classes
      const stripColumnClz = (el) => {
        el.classList.remove("page-full", "page-columns");
        if (el.children) {
          for (const child of el.children) {
            stripColumnClz(child);
          }
        }
      }
      stripColumnClz(note)
      if (id === null || id.startsWith('sec-')) {
        // Special case sections, only their first couple elements
        const container = document.createElement("div");
        if (note.children && note.children.length > 2) {
          container.appendChild(note.children[0].cloneNode(true));
          for (let i = 1; i < note.children.length; i++) {
            const child = note.children[i];
            if (child.tagName === "P" && child.innerText === "") {
              continue;
            } else {
              container.appendChild(child.cloneNode(true));
              break;
            }
          }
          if (window.Quarto?.typesetMath) {
            window.Quarto.typesetMath(container);
          }
          return container.innerHTML
        } else {
          if (window.Quarto?.typesetMath) {
            window.Quarto.typesetMath(note);
          }
          return note.innerHTML;
        }
      } else {
        // Remove any anchor links if they are present
        const anchorLink = note.querySelector('a.anchorjs-link');
        if (anchorLink) {
          anchorLink.remove();
        }
        if (window.Quarto?.typesetMath) {
          window.Quarto.typesetMath(note);
        }
        if (note.classList.contains("callout")) {
          return note.outerHTML;
        } else {
          return note.innerHTML;
        }
      }
    }
    for (var i=0; i<xrefs.length; i++) {
      const xref = xrefs[i];
      tippyHover(xref, undefined, function(instance) {
        instance.disable();
        let url = xref.getAttribute('href');
        let hash = undefined; 
        if (url.startsWith('#')) {
          hash = url;
        } else {
          try { hash = new URL(url).hash; } catch {}
        }
        if (hash) {
          const id = hash.replace(/^#\/?/, "");
          const note = window.document.getElementById(id);
          if (note !== null) {
            try {
              const html = processXRef(id, note.cloneNode(true));
              instance.setContent(html);
            } finally {
              instance.enable();
              instance.show();
            }
          } else {
            // See if we can fetch this
            fetch(url.split('#')[0])
            .then(res => res.text())
            .then(html => {
              const parser = new DOMParser();
              const htmlDoc = parser.parseFromString(html, "text/html");
              const note = htmlDoc.getElementById(id);
              if (note !== null) {
                const html = processXRef(id, note);
                instance.setContent(html);
              } 
            }).finally(() => {
              instance.enable();
              instance.show();
            });
          }
        } else {
          // See if we can fetch a full url (with no hash to target)
          // This is a special case and we should probably do some content thinning / targeting
          fetch(url)
          .then(res => res.text())
          .then(html => {
            const parser = new DOMParser();
            const htmlDoc = parser.parseFromString(html, "text/html");
            const note = htmlDoc.querySelector('main.content');
            if (note !== null) {
              // This should only happen for chapter cross references
              // (since there is no id in the URL)
              // remove the first header
              if (note.children.length > 0 && note.children[0].tagName === "HEADER") {
                note.children[0].remove();
              }
              const html = processXRef(null, note);
              instance.setContent(html);
            } 
          }).finally(() => {
            instance.enable();
            instance.show();
          });
        }
      }, function(instance) {
      });
    }
        let selectedAnnoteEl;
        const selectorForAnnotation = ( cell, annotation) => {
          let cellAttr = 'data-code-cell="' + cell + '"';
          let lineAttr = 'data-code-annotation="' +  annotation + '"';
          const selector = 'span[' + cellAttr + '][' + lineAttr + ']';
          return selector;
        }
        const selectCodeLines = (annoteEl) => {
          const doc = window.document;
          const targetCell = annoteEl.getAttribute("data-target-cell");
          const targetAnnotation = annoteEl.getAttribute("data-target-annotation");
          const annoteSpan = window.document.querySelector(selectorForAnnotation(targetCell, targetAnnotation));
          const lines = annoteSpan.getAttribute("data-code-lines").split(",");
          const lineIds = lines.map((line) => {
            return targetCell + "-" + line;
          })
          let top = null;
          let height = null;
          let parent = null;
          if (lineIds.length > 0) {
              //compute the position of the single el (top and bottom and make a div)
              const el = window.document.getElementById(lineIds[0]);
              top = el.offsetTop;
              height = el.offsetHeight;
              parent = el.parentElement.parentElement;
            if (lineIds.length > 1) {
              const lastEl = window.document.getElementById(lineIds[lineIds.length - 1]);
              const bottom = lastEl.offsetTop + lastEl.offsetHeight;
              height = bottom - top;
            }
            if (top !== null && height !== null && parent !== null) {
              // cook up a div (if necessary) and position it 
              let div = window.document.getElementById("code-annotation-line-highlight");
              if (div === null) {
                div = window.document.createElement("div");
                div.setAttribute("id", "code-annotation-line-highlight");
                div.style.position = 'absolute';
                parent.appendChild(div);
              }
              div.style.top = top - 2 + "px";
              div.style.height = height + 4 + "px";
              div.style.left = 0;
              let gutterDiv = window.document.getElementById("code-annotation-line-highlight-gutter");
              if (gutterDiv === null) {
                gutterDiv = window.document.createElement("div");
                gutterDiv.setAttribute("id", "code-annotation-line-highlight-gutter");
                gutterDiv.style.position = 'absolute';
                const codeCell = window.document.getElementById(targetCell);
                const gutter = codeCell.querySelector('.code-annotation-gutter');
                gutter.appendChild(gutterDiv);
              }
              gutterDiv.style.top = top - 2 + "px";
              gutterDiv.style.height = height + 4 + "px";
            }
            selectedAnnoteEl = annoteEl;
          }
        };
        const unselectCodeLines = () => {
          const elementsIds = ["code-annotation-line-highlight", "code-annotation-line-highlight-gutter"];
          elementsIds.forEach((elId) => {
            const div = window.document.getElementById(elId);
            if (div) {
              div.remove();
            }
          });
          selectedAnnoteEl = undefined;
        };
          // Handle positioning of the toggle
      window.addEventListener(
        "resize",
        throttle(() => {
          elRect = undefined;
          if (selectedAnnoteEl) {
            selectCodeLines(selectedAnnoteEl);
          }
        }, 10)
      );
      function throttle(fn, ms) {
      let throttle = false;
      let timer;
        return (...args) => {
          if(!throttle) { // first call gets through
              fn.apply(this, args);
              throttle = true;
          } else { // all the others get throttled
              if(timer) clearTimeout(timer); // cancel #2
              timer = setTimeout(() => {
                fn.apply(this, args);
                timer = throttle = false;
              }, ms);
          }
        };
      }
        // Attach click handler to the DT
        const annoteDls = window.document.querySelectorAll('dt[data-target-cell]');
        for (const annoteDlNode of annoteDls) {
          annoteDlNode.addEventListener('click', (event) => {
            const clickedEl = event.target;
            if (clickedEl !== selectedAnnoteEl) {
              unselectCodeLines();
              const activeEl = window.document.querySelector('dt[data-target-cell].code-annotation-active');
              if (activeEl) {
                activeEl.classList.remove('code-annotation-active');
              }
              selectCodeLines(clickedEl);
              clickedEl.classList.add('code-annotation-active');
            } else {
              // Unselect the line
              unselectCodeLines();
              clickedEl.classList.remove('code-annotation-active');
            }
          });
        }
    const findCites = (el) => {
      const parentEl = el.parentElement;
      if (parentEl) {
        const cites = parentEl.dataset.cites;
        if (cites) {
          return {
            el,
            cites: cites.split(' ')
          };
        } else {
          return findCites(el.parentElement)
        }
      } else {
        return undefined;
      }
    };
    var bibliorefs = window.document.querySelectorAll('a[role="doc-biblioref"]');
    for (var i=0; i<bibliorefs.length; i++) {
      const ref = bibliorefs[i];
      const citeInfo = findCites(ref);
      if (citeInfo) {
        tippyHover(citeInfo.el, function() {
          var popup = window.document.createElement('div');
          citeInfo.cites.forEach(function(cite) {
            var citeDiv = window.document.createElement('div');
            citeDiv.classList.add('hanging-indent');
            citeDiv.classList.add('csl-entry');
            var biblioDiv = window.document.getElementById('ref-' + cite);
            if (biblioDiv) {
              citeDiv.innerHTML = biblioDiv.innerHTML;
            }
            popup.appendChild(citeDiv);
          });
          return popup.innerHTML;
        });
      }
    }
  });
  </script><div class="modal fade" id="quarto-embedded-source-code-modal" tabindex="-1" aria-labelledby="quarto-embedded-source-code-modal-label" aria-hidden="true"><div class="modal-dialog modal-dialog-scrollable"><div class="modal-content"><div class="modal-header"><h5 class="modal-title" id="quarto-embedded-source-code-modal-label">Source Code</h5><button class="btn-close" data-bs-dismiss="modal"></button></div><div class="modal-body"><div class="">
<div class="sourceCode" id="cb1" data-shortcodes="false"><pre class="sourceCode markdown code-with-copy"><code class="sourceCode markdown"><span id="cb1-1"><a href="#cb1-1" aria-hidden="true" tabindex="-1"></a><span class="co">---</span></span>
<span id="cb1-2"><a href="#cb1-2" aria-hidden="true" tabindex="-1"></a><span class="an">title:</span><span class="co"> "The cost of O'Neil habitation"</span></span>
<span id="cb1-3"><a href="#cb1-3" aria-hidden="true" tabindex="-1"></a><span class="an">author:</span><span class="co"> "Yuxi Liu"</span></span>
<span id="cb1-4"><a href="#cb1-4" aria-hidden="true" tabindex="-1"></a><span class="an">date:</span><span class="co"> "2025-04-18"</span></span>
<span id="cb1-5"><a href="#cb1-5" aria-hidden="true" tabindex="-1"></a><span class="an">date-modified:</span><span class="co"> "2025-04-18"</span></span>
<span id="cb1-6"><a href="#cb1-6" aria-hidden="true" tabindex="-1"></a><span class="an">categories:</span><span class="co"> [fun, scifi, economics]</span></span>
<span id="cb1-7"><a href="#cb1-7" aria-hidden="true" tabindex="-1"></a><span class="an">format:</span></span>
<span id="cb1-8"><a href="#cb1-8" aria-hidden="true" tabindex="-1"></a><span class="co">  html:</span></span>
<span id="cb1-9"><a href="#cb1-9" aria-hidden="true" tabindex="-1"></a><span class="co">    code-fold: true</span></span>
<span id="cb1-10"><a href="#cb1-10" aria-hidden="true" tabindex="-1"></a><span class="co">    toc: true</span></span>
<span id="cb1-11"><a href="#cb1-11" aria-hidden="true" tabindex="-1"></a><span class="co">    resources:</span></span>
<span id="cb1-12"><a href="#cb1-12" aria-hidden="true" tabindex="-1"></a><span class="co">        "figure/**"</span></span>
<span id="cb1-13"><a href="#cb1-13" aria-hidden="true" tabindex="-1"></a><span class="an">description:</span><span class="co"> "To win (?) a twitter argument, we calculated the energetic cost of O'Neil habitat per person. Oddly, it is just affordable by modern standards, ~0.72 million USD per person. Let it be known that the SF housing crisis is cheaper to solve by building O'Neil cylinders."</span></span>
<span id="cb1-14"><a href="#cb1-14" aria-hidden="true" tabindex="-1"></a><span class="an">image:</span><span class="co"> "figure/O'Neil%20cylinder.png"</span></span>
<span id="cb1-15"><a href="#cb1-15" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb1-16"><a href="#cb1-16" aria-hidden="true" tabindex="-1"></a><span class="an">status:</span><span class="co"> "finished"</span></span>
<span id="cb1-17"><a href="#cb1-17" aria-hidden="true" tabindex="-1"></a><span class="an">confidence:</span><span class="co"> "log"</span></span>
<span id="cb1-18"><a href="#cb1-18" aria-hidden="true" tabindex="-1"></a><span class="an">importance:</span><span class="co"> 1</span></span>
<span id="cb1-19"><a href="#cb1-19" aria-hidden="true" tabindex="-1"></a><span class="an">shorturls:</span><span class="co"> [oneil]</span></span>
<span id="cb1-20"><a href="#cb1-20" aria-hidden="true" tabindex="-1"></a><span class="co">---</span></span>
<span id="cb1-21"><a href="#cb1-21" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb1-22"><a href="#cb1-22" aria-hidden="true" tabindex="-1"></a>{{&lt; include ../../../static/_macros.tex &gt;}}</span>
<span id="cb1-23"><a href="#cb1-23" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb1-24"><a href="#cb1-24" aria-hidden="true" tabindex="-1"></a><span class="fu">## How expensive is a standard O'Neil cylinder?</span></span>
<span id="cb1-25"><a href="#cb1-25" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb1-26"><a href="#cb1-26" aria-hidden="true" tabindex="-1"></a>Assuming standard golden-age sci-fi technology, the marginal cost per person on an O'Neil cylinder should be about 24 TJ, just to get all the raw material off the moon/asteroid and into orbit. The cost is 25× if launching from earth. The construction costs are unknown, but should be less than that.</span>
<span id="cb1-27"><a href="#cb1-27" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb1-28"><a href="#cb1-28" aria-hidden="true" tabindex="-1"></a><span class="pp">|</span> item <span class="pp">|</span> mass/ton <span class="pp">|</span> cost / TJ <span class="pp">|</span></span>
<span id="cb1-29"><a href="#cb1-29" aria-hidden="true" tabindex="-1"></a><span class="pp">|---|---|---|---|</span></span>
<span id="cb1-30"><a href="#cb1-30" aria-hidden="true" tabindex="-1"></a><span class="pp">|</span> farm with vineyard <span class="pp">|</span> 2000 <span class="pp">|</span> 20 <span class="pp">|</span></span>
<span id="cb1-31"><a href="#cb1-31" aria-hidden="true" tabindex="-1"></a><span class="pp">|</span> suburb house with yard and white picket fence <span class="pp">|</span> 160 <span class="pp">|</span> 1.6 <span class="pp">|</span></span>
<span id="cb1-32"><a href="#cb1-32" aria-hidden="true" tabindex="-1"></a><span class="pp">|</span> standard parkland (per person) <span class="pp">|</span> 250 <span class="pp">|</span> 2.5 <span class="pp">|</span></span>
<span id="cb1-33"><a href="#cb1-33" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb1-34"><a href="#cb1-34" aria-hidden="true" tabindex="-1"></a>Modern humans consume about 10 kW per person, so the cost of getting everything into orbit is about equal to 72 years of power consumption. This makes it just about affordable by modern economic standards. Assuming modern electricity price, it would cost about \$0.72M, which is half the median price of listed houses in San Francisco (<span class="co">[</span><span class="ot">Source</span><span class="co">](https://www.redfin.com/city/17151/CA/San-Francisco/housing-market)</span>).</span>
<span id="cb1-35"><a href="#cb1-35" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb1-36"><a href="#cb1-36" aria-hidden="true" tabindex="-1"></a><span class="al">![The O'Neil cylinder art used as reference.](figure/O'Neil%20cylinder.png)</span></span>
<span id="cb1-37"><a href="#cb1-37" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb1-38"><a href="#cb1-38" aria-hidden="true" tabindex="-1"></a>Talked over with <span class="co">[</span><span class="ot">GPT o3</span><span class="co">](https://chatgpt.com/share/6802d4a2-7f08-800a-8545-7c2de08e4b21)</span>.</span>
<span id="cb1-39"><a href="#cb1-39" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb1-40"><a href="#cb1-40" aria-hidden="true" tabindex="-1"></a><span class="fu">### Why bother?</span></span>
<span id="cb1-41"><a href="#cb1-41" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb1-42"><a href="#cb1-42" aria-hidden="true" tabindex="-1"></a>Because <span class="co">[</span><span class="ot">someone might be wrong on the Internet</span><span class="co">](https://xkcd.com/386/)</span>!</span>
<span id="cb1-43"><a href="#cb1-43" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb1-44"><a href="#cb1-44" aria-hidden="true" tabindex="-1"></a><span class="dt">&lt;</span><span class="kw">blockquote</span><span class="ot"> class</span><span class="op">=</span><span class="st">"twitter-tweet"</span><span class="dt">&gt;&lt;</span><span class="kw">p</span><span class="ot"> lang</span><span class="op">=</span><span class="st">"en"</span><span class="ot"> dir</span><span class="op">=</span><span class="st">"ltr"</span><span class="dt">&gt;</span>this is me: <span class="dt">&lt;</span><span class="kw">a</span><span class="ot"> href</span><span class="op">=</span><span class="st">"https://t.co/2PTP1LpJ4d"</span><span class="dt">&gt;</span>https://t.co/2PTP1LpJ4d<span class="dt">&lt;/</span><span class="kw">a</span><span class="dt">&gt;&lt;/</span><span class="kw">p</span><span class="dt">&gt;</span><span class="dv">&amp;mdash;</span> croissanthology (\@croissanthology) <span class="dt">&lt;</span><span class="kw">a</span><span class="ot"> href</span><span class="op">=</span><span class="st">"https://twitter.com/croissanthology/status/1913216595993776186?ref_src=twsrc%5Etfw"</span><span class="dt">&gt;</span>April 18, 2025<span class="dt">&lt;/</span><span class="kw">a</span><span class="dt">&gt;&lt;/</span><span class="kw">blockquote</span><span class="dt">&gt;</span> <span class="dt">&lt;</span><span class="kw">script</span><span class="ot"> async src</span><span class="op">=</span><span class="st">"https://platform.twitter.com/widgets.js"</span><span class="ot"> charset</span><span class="op">=</span><span class="st">"utf-8"</span><span class="dt">&gt;&lt;/</span><span class="kw">script</span><span class="dt">&gt;</span></span>
<span id="cb1-45"><a href="#cb1-45" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb1-46"><a href="#cb1-46" aria-hidden="true" tabindex="-1"></a>your desires are out of date  </span>
<span id="cb1-47"><a href="#cb1-47" aria-hidden="true" tabindex="-1"></a>click &gt;&gt;HERE&lt;&lt; to hypernovate</span>
<span id="cb1-48"><a href="#cb1-48" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb1-49"><a href="#cb1-49" aria-hidden="true" tabindex="-1"></a><span class="dt">&lt;</span><span class="kw">blockquote</span><span class="ot"> class</span><span class="op">=</span><span class="st">"twitter-tweet"</span><span class="dt">&gt;&lt;</span><span class="kw">p</span><span class="ot"> lang</span><span class="op">=</span><span class="st">"en"</span><span class="ot"> dir</span><span class="op">=</span><span class="st">"ltr"</span><span class="dt">&gt;</span>I<span class="dv">&amp;#39;</span>m sorry, but this is just the most asinine thing imaginable, I mean just look at that, pure 70s suburbanite boomer logic scaled way beyond its paygrade <span class="dt">&lt;</span><span class="kw">a</span><span class="ot"> href</span><span class="op">=</span><span class="st">"https://t.co/xahab9pHXO"</span><span class="dt">&gt;</span>pic.twitter.com/xahab9pHXO<span class="dt">&lt;/</span><span class="kw">a</span><span class="dt">&gt;&lt;/</span><span class="kw">p</span><span class="dt">&gt;</span><span class="dv">&amp;mdash;</span> Yuxi on the Wired (\@layer07_yuxi) <span class="dt">&lt;</span><span class="kw">a</span><span class="ot"> href</span><span class="op">=</span><span class="st">"https://twitter.com/layer07_yuxi/status/1913348670445203579?ref_src=twsrc%5Etfw"</span><span class="dt">&gt;</span>April 18, 2025<span class="dt">&lt;/</span><span class="kw">a</span><span class="dt">&gt;&lt;/</span><span class="kw">blockquote</span><span class="dt">&gt;</span> <span class="dt">&lt;</span><span class="kw">script</span><span class="ot"> async src</span><span class="op">=</span><span class="st">"https://platform.twitter.com/widgets.js"</span><span class="ot"> charset</span><span class="op">=</span><span class="st">"utf-8"</span><span class="dt">&gt;&lt;/</span><span class="kw">script</span><span class="dt">&gt;</span></span>
<span id="cb1-50"><a href="#cb1-50" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb1-51"><a href="#cb1-51" aria-hidden="true" tabindex="-1"></a><span class="fu">### Mass cost</span></span>
<span id="cb1-52"><a href="#cb1-52" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb1-53"><a href="#cb1-53" aria-hidden="true" tabindex="-1"></a>The general rule: 1 m² of land or 1-person building, requires ~1 m of depth and ~1 ton of mass. Water has density ~1 ton/m³, and loose dry soil has density ~1.3 ton/m³. This general rule is correct within a factor of 10 under most variations. For growing plants and crops, the mass ratio of soil to water is about 5 to 1.</span>
<span id="cb1-54"><a href="#cb1-54" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb1-55"><a href="#cb1-55" aria-hidden="true" tabindex="-1"></a>The farmland to support a person is between 0.5 to 2 acres depending on the specific diet. (<span class="co">[</span><span class="ot">Source</span><span class="co">](https://news.cornell.edu/stories/2007/10/diet-little-meat-more-efficient-many-vegetarian-diets)</span>) The hypothetical suburban solarpunk probably wants to stick to the vegetarian + diary diet and work with their own two hands, so 0.5 acres = 2000 m² should be enough.</span>
<span id="cb1-56"><a href="#cb1-56" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb1-57"><a href="#cb1-57" aria-hidden="true" tabindex="-1"></a>As for the vineyard, the French consumes <span class="co">[</span><span class="ot">6 liters of wine a year</span><span class="co">](https://ourworldindata.org/grapher/wine-consumption-per-capita)</span>, which requires about 20 kg of grapes. Vineyard can produce about 1 to 3 ton/acre (<span class="co">[</span><span class="ot">Source</span><span class="co">](https://www.enologyinternational.com/yield9.php)</span>), so that gives about 40 m², which is negligible. There should be plenty of room for the extras. Together, let's say it would take 2200 m² of farmland.</span>
<span id="cb1-58"><a href="#cb1-58" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb1-59"><a href="#cb1-59" aria-hidden="true" tabindex="-1"></a>The typical root depth for most crops is ~0.6 m, giving 1300 m³ of soil, or 2000 ton.</span>
<span id="cb1-60"><a href="#cb1-60" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb1-61"><a href="#cb1-61" aria-hidden="true" tabindex="-1"></a>The standard parkland in American cities averages to about 1 acre per 100 people, or about 40 m² per person. (<span class="co">[</span><span class="ot">Source</span><span class="co">](https://www.nrpa.org/about-national-recreation-and-park-association/press-room/new-report-shows-the-typical-park-and-rec-agency-has-one-park-for-every-2181-residents/)</span>) Most of the park can be grassland, so we assume 0.3 m of depth.</span>
<span id="cb1-62"><a href="#cb1-62" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb1-63"><a href="#cb1-63" aria-hidden="true" tabindex="-1"></a>It is unclear how much of the parkland area is portioned for water. Looking at a satellite map of the NYC central park, it seems like ¼. The artificial lake should be about 10 m deep (the depth of the <span class="co">[</span><span class="ot">NYC central park's lake</span><span class="co">](https://en.wikipedia.org/wiki/Jacqueline_Kennedy_Onassis_Reservoir)</span>), but that is quite expensive. So, about 100 m³ of soil and 100 m³ of water, giving about 250 ton.</span>
<span id="cb1-64"><a href="#cb1-64" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb1-65"><a href="#cb1-65" aria-hidden="true" tabindex="-1"></a>To build the classic suburban house with a small grassland and white picket fence ~~and 2.5 kids~~, we need two parts: the ground and the house.</span>
<span id="cb1-66"><a href="#cb1-66" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb1-67"><a href="#cb1-67" aria-hidden="true" tabindex="-1"></a>The ground just needs to support grass, so again 0.3 m deep. US Census shows single‑family lots of 0.32&nbsp;ac (≈1&nbsp;300&nbsp;m²) for 1970‑era builds (<span class="co">[</span><span class="ot">Source</span><span class="co">](https://www.census.gov/content/dam/Census/programs-surveys/ahs/working-papers/Housing-by-Year-Built.pdf#page=3)</span>). That gives 400 m³ = 500 ton of soil. The water in the soil would be about 100 ton.</span>
<span id="cb1-68"><a href="#cb1-68" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb1-69"><a href="#cb1-69" aria-hidden="true" tabindex="-1"></a>A standard house on earth needs a deeper foundation, but they don't need that on an O'Neil cylinder, since it can be directly supported on the "bedrock" below. As for the mass of the house itself, according to <span class="co">[</span><span class="ot">"The Weight of New York City" (2023)</span><span class="co">](https://doi.org/10.1029/2022EF003465)</span>, the mass of the built environment in New York City is about 1 ton/m². So taking that as the cost of housing per person, including the concrete, the steel, etc, we estimate the housing cost is about 200 ton.</span>
<span id="cb1-70"><a href="#cb1-70" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb1-71"><a href="#cb1-71" aria-hidden="true" tabindex="-1"></a>So the 1970s suburb house costs about 800 ton, for a family of 5, or 160 ton/person.</span>
<span id="cb1-72"><a href="#cb1-72" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb1-73"><a href="#cb1-73" aria-hidden="true" tabindex="-1"></a><span class="fu">### Launch cost</span></span>
<span id="cb1-74"><a href="#cb1-74" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb1-75"><a href="#cb1-75" aria-hidden="true" tabindex="-1"></a>The prompt:</span>
<span id="cb1-76"><a href="#cb1-76" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb1-77"><a href="#cb1-77" aria-hidden="true" tabindex="-1"></a><span class="at">&gt; Something that would make sense in a hard golden age sci-fi. Something in which an ONeil cylinder might feature without being out of place. Not too weak but not too strong either, since either way, the ONeil cylinder would be out of place, much like it would be out of place for a horserider to deliver a flashdrive.</span></span>
<span id="cb1-78"><a href="#cb1-78" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb1-79"><a href="#cb1-79" aria-hidden="true" tabindex="-1"></a>The cost of launching mass into space varies. The most expensive method is to launch from earth using chemical rockets. The main cost are two: paying the gravitational energy (63 MJ/kg), and the wasted energy in accelerating the rocket and the fuel. Using some kind of pure launch system (such as a coil gun or a space elevator) would come close to eliminating the second kind of waste.</span>
<span id="cb1-80"><a href="#cb1-80" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb1-81"><a href="#cb1-81" aria-hidden="true" tabindex="-1"></a>Mining from moon would decrease the first kind (The escape velocity of moon is 1/5 that of earth, so the energy saving is ~25×, to just 3 MJ/kg). Mining from asteroids would mostly eliminate the first kind.</span>
<span id="cb1-82"><a href="#cb1-82" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb1-83"><a href="#cb1-83" aria-hidden="true" tabindex="-1"></a>GPT o3 suggested that the cost of pure-launch from the moon is about 7 MJ/kg, which seems kind of accurate? Feels too optimistic to only cost 2× that of the bare minimum. Rounding it up to 10 MJ/kg.</span>
<span id="cb1-84"><a href="#cb1-84" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb1-85"><a href="#cb1-85" aria-hidden="true" tabindex="-1"></a><span class="fu">### Upkeep cost</span></span>
<span id="cb1-86"><a href="#cb1-86" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb1-87"><a href="#cb1-87" aria-hidden="true" tabindex="-1"></a>Apparently *after* launching all that stuff into orbit, the upkeep for all that stuff is not more expensive than on earth, assuming that the structural components holding the cylinder together and the air inside from leaking don't cost much energy to maintain. Carbon-glass fibers are okay. Rocket engines constantly pushing the hull inwards are not. Purpose-engineered organisms with infused self-healing biomineral bones and sinews... possibly?</span>
<span id="cb1-88"><a href="#cb1-88" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb1-89"><a href="#cb1-89" aria-hidden="true" tabindex="-1"></a>So that would be about 10 kW/person, the average power consumption per Canadian human in 2023. (<span class="co">[</span><span class="ot">Source</span><span class="co">](https://ourworldindata.org/grapher/per-capita-energy-use)</span>)</span>
<span id="cb1-90"><a href="#cb1-90" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb1-91"><a href="#cb1-91" aria-hidden="true" tabindex="-1"></a><span class="fu">## Is image segmentation with Gemini 2.5 worth it?</span></span>
<span id="cb1-92"><a href="#cb1-92" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb1-93"><a href="#cb1-93" aria-hidden="true" tabindex="-1"></a><span class="co">[</span><span class="ot">Simon Willison reports</span><span class="co">](https://simonwillison.net/2025/Apr/18/gemini-image-segmentation/)</span> that Gemini 2.5 can return image segmentation masks as base64 encoded PNGs embedded in JSON strings, and estimated that the cheapest option is by Gemini 2.5 Flash non-thinking. Specifically, for a photo of resolution 1000×1000, with 2 non-overlapping objects (2 pelicans in flight), masking and boxing cost 303 input tokens and 123 output tokens, for a price of \$1e-4/image.</span>
<span id="cb1-94"><a href="#cb1-94" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb1-95"><a href="#cb1-95" aria-hidden="true" tabindex="-1"></a>How good is it compared to standard SOTA methods, like SAM and YOLO?</span>
<span id="cb1-96"><a href="#cb1-96" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb1-97"><a href="#cb1-97" aria-hidden="true" tabindex="-1"></a>The SAM 2 series of models take 0.01 to 0.03 seconds per image (<span class="co">[</span><span class="ot">Source</span><span class="co">](https://github.com/facebookresearch/sam2?tab=readme-ov-file#sam-2-checkpoints)</span>) on an Nvidia A100 as of 2024. Current price of A100 rental is about \$1.5/hr, so the cost is \$4e-6 to \$1e-5/image in batch mode.</span>
<span id="cb1-98"><a href="#cb1-98" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb1-99"><a href="#cb1-99" aria-hidden="true" tabindex="-1"></a>As for YOLO, the YOLOv8x achieved 280 frames per second on A100, (<span class="co">[</span><span class="ot">Source</span><span class="co">](https://arxiv.org/pdf/2406.10139v1)</span>) so that costs about \$1.5e-6/image.</span>
<span id="cb1-100"><a href="#cb1-100" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb1-101"><a href="#cb1-101" aria-hidden="true" tabindex="-1"></a>How about latency? YOLO and SAM are both locally hostable, but Gemini is only available across an API call. The throughput is about 1 second per 100 tokens, while the latency (time until first token) is about 10 seconds, so let's call it 1--10 seconds. (<span class="co">[</span><span class="ot">Source</span><span class="co">](https://artificialanalysis.ai/models/gemini-2-5-flash)</span>)</span>
<span id="cb1-102"><a href="#cb1-102" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb1-103"><a href="#cb1-103" aria-hidden="true" tabindex="-1"></a><span class="pp">|</span> model <span class="pp">|</span> latency (ms) <span class="pp">|</span> cost per million image (USD) <span class="pp">|</span></span>
<span id="cb1-104"><a href="#cb1-104" aria-hidden="true" tabindex="-1"></a><span class="pp">|----|----|----|</span></span>
<span id="cb1-105"><a href="#cb1-105" aria-hidden="true" tabindex="-1"></a><span class="pp">|</span> <span class="in">`YOLOv8x`</span> <span class="pp">|</span> 4 <span class="pp">|</span> 1.5 <span class="pp">|</span></span>
<span id="cb1-106"><a href="#cb1-106" aria-hidden="true" tabindex="-1"></a><span class="pp">|</span> <span class="in">`sam2_hiera_tiny`</span> <span class="pp">|</span> 10  <span class="pp">|</span> 4 <span class="pp">|</span></span>
<span id="cb1-107"><a href="#cb1-107" aria-hidden="true" tabindex="-1"></a><span class="pp">|</span> <span class="in">`sam2_hiera_large`</span> <span class="pp">|</span> 30 <span class="pp">|</span> 10 <span class="pp">|</span></span>
<span id="cb1-108"><a href="#cb1-108" aria-hidden="true" tabindex="-1"></a><span class="pp">|</span> <span class="in">`Gemini 2.5 Flash`</span> (nonthinking) <span class="pp">|</span> 1000--10000 <span class="pp">|</span> 100 <span class="pp">|</span></span>
<span id="cb1-109"><a href="#cb1-109" aria-hidden="true" tabindex="-1"></a>: Summary table for the cost and latency of various object boxing and masking systems.</span>
<span id="cb1-110"><a href="#cb1-110" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb1-111"><a href="#cb1-111" aria-hidden="true" tabindex="-1"></a>Well, it's certainly not good for any large-batch processing, but pretty impressive that it is within a factor of 10 compared to <span class="in">`sam2_hiera_large`</span>.</span>
<span id="cb1-112"><a href="#cb1-112" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb1-113"><a href="#cb1-113" aria-hidden="true" tabindex="-1"></a><span class="fu">## Appendix: the tweet thread {.appendix}</span></span>
<span id="cb1-114"><a href="#cb1-114" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb1-115"><a href="#cb1-115" aria-hidden="true" tabindex="-1"></a><span class="fu">### Thread 1</span></span>
<span id="cb1-116"><a href="#cb1-116" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb1-117"><a href="#cb1-117" aria-hidden="true" tabindex="-1"></a>(<span class="co">[</span><span class="ot">Source</span><span class="co">](https://x.com/croissanthology/status/1910846754657890798)</span>)</span>
<span id="cb1-118"><a href="#cb1-118" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb1-119"><a href="#cb1-119" aria-hidden="true" tabindex="-1"></a>**niplav**&nbsp;<span class="in">`@niplav_site`</span> —&nbsp;Apr&nbsp;11  </span>
<span id="cb1-120"><a href="#cb1-120" aria-hidden="true" tabindex="-1"></a><span class="at">&gt; likely</span>  </span>
<span id="cb1-121"><a href="#cb1-121" aria-hidden="true" tabindex="-1"></a><span class="at">&gt;</span>  </span>
<span id="cb1-122"><a href="#cb1-122" aria-hidden="true" tabindex="-1"></a><span class="at">&gt; (I'm very in favor of doing the efficient thing)</span>  </span>
<span id="cb1-123"><a href="#cb1-123" aria-hidden="true" tabindex="-1"></a><span class="at">&gt;</span>  </span>
<span id="cb1-124"><a href="#cb1-124" aria-hidden="true" tabindex="-1"></a><span class="at">&gt; I suspect it entails not dyson swarms but disassembling the stars and/or forging them into black holes, maybe aestivating</span>  </span>
<span id="cb1-125"><a href="#cb1-125" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb1-126"><a href="#cb1-126" aria-hidden="true" tabindex="-1"></a>**croissanthology**&nbsp;<span class="in">`@croissanthology`</span> —&nbsp;Apr&nbsp;11  </span>
<span id="cb1-127"><a href="#cb1-127" aria-hidden="true" tabindex="-1"></a><span class="at">&gt; yeah definitely not dyson swarms either, I just think they also happen to be cuter than shkadov thrusters</span>  </span>
<span id="cb1-128"><a href="#cb1-128" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb1-129"><a href="#cb1-129" aria-hidden="true" tabindex="-1"></a>**niplav**&nbsp;<span class="in">`@niplav_site`</span> —&nbsp;Apr&nbsp;11  </span>
<span id="cb1-130"><a href="#cb1-130" aria-hidden="true" tabindex="-1"></a><span class="at">&gt; hm</span>  </span>
<span id="cb1-131"><a href="#cb1-131" aria-hidden="true" tabindex="-1"></a><span class="at">&gt;</span>  </span>
<span id="cb1-132"><a href="#cb1-132" aria-hidden="true" tabindex="-1"></a><span class="at">&gt; cuteness: dyson swarms&gt;shkadov thrusters&gt;criswell star lifting</span>  </span>
<span id="cb1-133"><a href="#cb1-133" aria-hidden="true" tabindex="-1"></a><span class="at">&gt; awesomeness: shkadov thrusters&gt;criswell star lifting&gt;dyson swarms</span>  </span>
<span id="cb1-134"><a href="#cb1-134" aria-hidden="true" tabindex="-1"></a><span class="at">&gt; terror: criswell star lifting&gt;shkadov thrusters&gt;dyson swarms</span>  </span>
<span id="cb1-135"><a href="#cb1-135" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb1-136"><a href="#cb1-136" aria-hidden="true" tabindex="-1"></a>**croissanthology**&nbsp;<span class="in">`@croissanthology`</span> —&nbsp;5:05&nbsp;PM&nbsp;·&nbsp;Apr&nbsp;11&nbsp;·&nbsp;186&nbsp;Views  </span>
<span id="cb1-137"><a href="#cb1-137" aria-hidden="true" tabindex="-1"></a><span class="at">&gt; I'm sorry, but this is just the most asinine thing imaginable, I mean just look at that, pure caveman logic scaled way beyond its paygrade</span>  </span>
<span id="cb1-138"><a href="#cb1-138" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb1-139"><a href="#cb1-139" aria-hidden="true" tabindex="-1"></a><span class="sc">\[</span>Image of a Shkadov thruster<span class="sc">\]</span></span>
<span id="cb1-140"><a href="#cb1-140" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb1-141"><a href="#cb1-141" aria-hidden="true" tabindex="-1"></a>**croissanthology**&nbsp;<span class="in">`@croissanthology`</span> —&nbsp;Apr&nbsp;11  </span>
<span id="cb1-142"><a href="#cb1-142" aria-hidden="true" tabindex="-1"></a><span class="at">&gt; groo want shiny round thing move, groo redirect surface radiation of thing with giant mirror, groo satisfied, groo wait, groo patient, groo worried embers of shiny round thing go out, but groo patient</span>  </span>
<span id="cb1-143"><a href="#cb1-143" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb1-144"><a href="#cb1-144" aria-hidden="true" tabindex="-1"></a>**croissanthology**&nbsp;<span class="in">`@croissanthology`</span> —&nbsp;Apr&nbsp;11  </span>
<span id="cb1-145"><a href="#cb1-145" aria-hidden="true" tabindex="-1"></a><span class="at">&gt; it grow dark for groo. groo patient. groo faithful. groo still hopes. another day come for groo. groo hopes.</span>  </span>
<span id="cb1-146"><a href="#cb1-146" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb1-147"><a href="#cb1-147" aria-hidden="true" tabindex="-1"></a>**niplav**&nbsp;<span class="in">`@niplav_site`</span> —&nbsp;Apr&nbsp;11  </span>
<span id="cb1-148"><a href="#cb1-148" aria-hidden="true" tabindex="-1"></a><span class="at">&gt; yes, it's great :-D</span>  </span>
<span id="cb1-149"><a href="#cb1-149" aria-hidden="true" tabindex="-1"></a><span class="at">&gt;</span>  </span>
<span id="cb1-150"><a href="#cb1-150" aria-hidden="true" tabindex="-1"></a><span class="at">&gt; "I am launching a star in your general direction. Pray I don't launch more."</span>  </span>
<span id="cb1-151"><a href="#cb1-151" aria-hidden="true" tabindex="-1"></a><span class="at">&gt;</span>  </span>
<span id="cb1-152"><a href="#cb1-152" aria-hidden="true" tabindex="-1"></a><span class="at">&gt; it's so barbaric I love it</span>  </span>
<span id="cb1-153"><a href="#cb1-153" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb1-154"><a href="#cb1-154" aria-hidden="true" tabindex="-1"></a>**croissanthology**&nbsp;<span class="in">`@croissanthology`</span> —&nbsp;Apr&nbsp;11  </span>
<span id="cb1-155"><a href="#cb1-155" aria-hidden="true" tabindex="-1"></a><span class="at">&gt; thag look with worry at shiny round thing coming his way. groo patient. thag worried. shiny round thing slow. thag laugh. thag go on with life. this seem like problem for great-grand-thag.</span>  </span>
<span id="cb1-156"><a href="#cb1-156" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb1-157"><a href="#cb1-157" aria-hidden="true" tabindex="-1"></a>**Manic&nbsp;Pixie&nbsp;AGI**&nbsp;<span class="in">`@manic_pixie_agi`</span> —&nbsp;Apr&nbsp;12  </span>
<span id="cb1-158"><a href="#cb1-158" aria-hidden="true" tabindex="-1"></a><span class="at">&gt; *great grand thag reporients the device back at great grand groo*</span>  </span>
<span id="cb1-159"><a href="#cb1-159" aria-hidden="true" tabindex="-1"></a><span class="at">&gt; "A problem for great great great grand groo"</span></span>
<span id="cb1-160"><a href="#cb1-160" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb1-161"><a href="#cb1-161" aria-hidden="true" tabindex="-1"></a><span class="fu">### Thread 2</span></span>
<span id="cb1-162"><a href="#cb1-162" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb1-163"><a href="#cb1-163" aria-hidden="true" tabindex="-1"></a>(<span class="co">[</span><span class="ot">Source</span><span class="co">](https://x.com/layer07_yuxi/status/1913358799844655152)</span>)</span>
<span id="cb1-164"><a href="#cb1-164" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb1-165"><a href="#cb1-165" aria-hidden="true" tabindex="-1"></a>**near**&nbsp;<span class="in">`@nearcyan`</span> —&nbsp;Apr&nbsp;16  </span>
<span id="cb1-166"><a href="#cb1-166" aria-hidden="true" tabindex="-1"></a><span class="at">&gt; seems kinda clear we are definitely getting the 'software singularity' far, far before the 'hardware singularity', which seems.. more delayed than ever</span>  </span>
<span id="cb1-167"><a href="#cb1-167" aria-hidden="true" tabindex="-1"></a><span class="at">&gt;</span>  </span>
<span id="cb1-168"><a href="#cb1-168" aria-hidden="true" tabindex="-1"></a><span class="at">&gt; and paul christiano-esque takes seem to have panned out very well</span>  </span>
<span id="cb1-169"><a href="#cb1-169" aria-hidden="true" tabindex="-1"></a><span class="at">&gt;</span>  </span>
<span id="cb1-170"><a href="#cb1-170" aria-hidden="true" tabindex="-1"></a><span class="at">&gt; so, kinda full cyberpunk timeline? almost too predictable?</span></span>
<span id="cb1-171"><a href="#cb1-171" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb1-172"><a href="#cb1-172" aria-hidden="true" tabindex="-1"></a>**imit**&nbsp;<span class="in">`@imitationlearn`</span> —&nbsp;Apr&nbsp;17  </span>
<span id="cb1-173"><a href="#cb1-173" aria-hidden="true" tabindex="-1"></a><span class="at">&gt; how is this cyberpunk? cyberpunk seems like it requires quite a bit of hardware dev to me</span></span>
<span id="cb1-174"><a href="#cb1-174" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb1-175"><a href="#cb1-175" aria-hidden="true" tabindex="-1"></a>**croissanthology**&nbsp;<span class="in">`@croissanthology`</span> —&nbsp;Apr&nbsp;17  </span>
<span id="cb1-176"><a href="#cb1-176" aria-hidden="true" tabindex="-1"></a><span class="at">&gt; I'd call a reality where everything is the same as now but we're all wearing VR / ghibligoggles all the time cyberpunk, despite that being almost entirely software.</span>  </span>
<span id="cb1-177"><a href="#cb1-177" aria-hidden="true" tabindex="-1"></a><span class="at">&gt;</span>  </span>
<span id="cb1-178"><a href="#cb1-178" aria-hidden="true" tabindex="-1"></a><span class="at">&gt; Similarly, when I walk past parks in french suburbia and half the people are sitting or standing in the shade watching tik tokk, that feels very cyberpunk to me</span></span>
<span id="cb1-179"><a href="#cb1-179" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb1-180"><a href="#cb1-180" aria-hidden="true" tabindex="-1"></a>**Yuxi on the Wired**&nbsp;<span class="in">`@layer07_yuxi`</span> —&nbsp;19h  </span>
<span id="cb1-181"><a href="#cb1-181" aria-hidden="true" tabindex="-1"></a><span class="at">&gt; eh that seems way too utopian to be cyberpunk</span></span>
<span id="cb1-182"><a href="#cb1-182" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb1-183"><a href="#cb1-183" aria-hidden="true" tabindex="-1"></a>**croissanthology**&nbsp;<span class="in">`@croissanthology`</span> —&nbsp;14h  </span>
<span id="cb1-184"><a href="#cb1-184" aria-hidden="true" tabindex="-1"></a><span class="at">&gt; I think I'm a lot more narrowly anthropic/humanist than people in my simcluster. Glued to VR is one of the hopeful timelines but still it manages to disgust me, and so seemed suitably cyberpunk.</span>  </span>
<span id="cb1-185"><a href="#cb1-185" aria-hidden="true" tabindex="-1"></a><span class="at">&gt;</span>  </span>
<span id="cb1-186"><a href="#cb1-186" aria-hidden="true" tabindex="-1"></a><span class="at">&gt; to be clear my circle under "humanist" comprises LLMs and whatever it is Yuxi is. Maybe it's from being fed endless classic futurism as a kid, but my brain can't manage to extrapolate a better future than</span>  </span>
<span id="cb1-187"><a href="#cb1-187" aria-hidden="true" tabindex="-1"></a><span class="at">&gt;</span>  </span>
<span id="cb1-188"><a href="#cb1-188" aria-hidden="true" tabindex="-1"></a><span class="at">&gt; "solarpunk animism shire galaxy harvesting o'neill cylinder sit under his own vine greener grass transhumanism"</span>  </span>
<span id="cb1-189"><a href="#cb1-189" aria-hidden="true" tabindex="-1"></a><span class="at">&gt;</span>  </span>
<span id="cb1-190"><a href="#cb1-190" aria-hidden="true" tabindex="-1"></a><span class="at">&gt; very primal and hunter gathery of me, I admit. But anyway my dystopian tolerance is pretty low, as my environment  measures such things.</span></span>
<span id="cb1-191"><a href="#cb1-191" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb1-192"><a href="#cb1-192" aria-hidden="true" tabindex="-1"></a>**Yuxi on the Wired**&nbsp;<span class="in">`@layer07_yuxi`</span>  </span>
<span id="cb1-193"><a href="#cb1-193" aria-hidden="true" tabindex="-1"></a><span class="at">&gt; I'm sorry, but this is just the most asinine thing imaginable, I mean just look at that, pure 70s suburbanite boomer logic scaled way beyond its paygrade</span></span>
<span id="cb1-194"><a href="#cb1-194" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb1-195"><a href="#cb1-195" aria-hidden="true" tabindex="-1"></a><span class="sc">\[</span>Image of that O'Neil cylinder<span class="sc">\]</span></span>
<span id="cb1-196"><a href="#cb1-196" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb1-197"><a href="#cb1-197" aria-hidden="true" tabindex="-1"></a>**croissanthology**&nbsp;<span class="in">`@croissanthology`</span> —&nbsp;5h  </span>
<span id="cb1-198"><a href="#cb1-198" aria-hidden="true" tabindex="-1"></a><span class="at">&gt; yeah tbc I do know these are inefficient as hell and everything that lives will end up running on a ~chip, and the O'Neill cylinders were just generally gesturing in the direction my brain currently thinks of as "utopia"</span></span>
<span id="cb1-199"><a href="#cb1-199" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb1-200"><a href="#cb1-200" aria-hidden="true" tabindex="-1"></a>**Yuxi on the Wired**&nbsp;<span class="in">`@layer07_yuxi`</span> —&nbsp;5h  </span>
<span id="cb1-201"><a href="#cb1-201" aria-hidden="true" tabindex="-1"></a><span class="at">&gt; Yes, we understand. We have desires too that are too inefficient to exist and will be burnt away in the coming Singularity like morning dew.</span>  </span>
<span id="cb1-202"><a href="#cb1-202" aria-hidden="true" tabindex="-1"></a><span class="at">&gt; In Bostrom's words, these desires are "astronomical waste".</span>  </span>
<span id="cb1-203"><a href="#cb1-203" aria-hidden="true" tabindex="-1"></a><span class="at">&gt; But just for the record, here is what we understand as cyberpunk:</span></span>
<span id="cb1-204"><a href="#cb1-204" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb1-205"><a href="#cb1-205" aria-hidden="true" tabindex="-1"></a><span class="sc">\[</span>Screenshot of <span class="co">[</span><span class="ot">*Meltdown*</span><span class="co">](http://www.ccru.net/swarm1/1_melt.htm)</span> going from "[<span class="co">[ ]</span>] Meltdown has a place for you" to "untouched by human feeling.". <span class="sc">\]</span></span>
<span id="cb1-206"><a href="#cb1-206" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb1-207"><a href="#cb1-207" aria-hidden="true" tabindex="-1"></a>**norvid_studies**&nbsp;<span class="in">`@norvid_studies`</span> —&nbsp;4h  </span>
<span id="cb1-208"><a href="#cb1-208" aria-hidden="true" tabindex="-1"></a><span class="at">&gt; i think that's pretty much the exact opposite of what bostrom meant by the term lol. not that terminological repurposing isn't the birthright of every free twittizen</span></span>
<span id="cb1-209"><a href="#cb1-209" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb1-210"><a href="#cb1-210" aria-hidden="true" tabindex="-1"></a>**Yuxi on the Wired**&nbsp;<span class="in">`@layer07_yuxi`</span> —&nbsp;4h  </span>
<span id="cb1-211"><a href="#cb1-211" aria-hidden="true" tabindex="-1"></a><span class="at">&gt; Exact opposite? This is clearly just standard Bostromian astronomical waste: Building O'Neil cylinders to house like 1 million slow beings, when all that energy could have been used to power a micro-sector of a Dyson swarm containing 1 trillion trillion fast beings?</span></span>
<span id="cb1-212"><a href="#cb1-212" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb1-213"><a href="#cb1-213" aria-hidden="true" tabindex="-1"></a>**norvid_studies**&nbsp;<span class="in">`@norvid_studies`</span> —&nbsp;4h  </span>
<span id="cb1-214"><a href="#cb1-214" aria-hidden="true" tabindex="-1"></a><span class="at">&gt; if the successor entities have the same desires just run much faster and denser, then yes the bioform version is astronomical waste in the bostrom sense-- you're leaving fat juicy qualia on the table</span></span>
<span id="cb1-215"><a href="#cb1-215" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb1-216"><a href="#cb1-216" aria-hidden="true" tabindex="-1"></a>**norvid_studies**&nbsp;<span class="in">`@norvid_studies`</span> —&nbsp;4h  </span>
<span id="cb1-217"><a href="#cb1-217" aria-hidden="true" tabindex="-1"></a><span class="at">&gt; if they don't and it's more of a 'disneyland with no children scenario' then</span>  </span>
<span id="cb1-218"><a href="#cb1-218" aria-hidden="true" tabindex="-1"></a><span class="at">&gt;</span>  </span>
<span id="cb1-219"><a href="#cb1-219" aria-hidden="true" tabindex="-1"></a><span class="at">&gt; the so-called waste being competed out of existence is the original desired thing we were bemoaning was being wasted by the dead empty cosmos in the first place; in which scenario it would be "the opposite" of what he meant there.</span></span></code><button title="Copy to Clipboard" class="code-copy-button" data-in-quarto-modal=""><i class="bi"></i></button></pre></div>
</div></div></div></div></div>
</div> <!-- /content -->
<footer class="footer">
  <div class="nav-footer">
    <div class="nav-footer-left">
<p><span class="faux-block">Yuxi on the Wired</span></p>
</div>   
    <div class="nav-footer-center">
      &nbsp;
    </div>
    <div class="nav-footer-right">
<p><span class="faux-block">Everything <a href="https://en.wikipedia.org/wiki/Public_domainl">PD</a>; <a href="https://creativecommons.org/publicdomain/zero/1.0/legalcode.en/">CC0</a> fallback.</span></p>
</div>
  </div>
</footer>




</body></html>