---
title: "Sketches"
listing:
  date-format: iso
  contents: posts
  fields: [image, title, categories, description, reading-time,
           date, file-modified]
  sort: "date desc"
  type: default
  categories: true
  feed:
    title: "Yuxi on the Wired - Sketches"
    language: en
    items: 10
    type: partial
  sort-ui: false
  filter-ui: false
page-layout: full
title-block-banner: true
---

I make my writing in a simple 3-stage process: private draft, public draft, public finished essay.

The private draft is a collection of works in progress and lightly edited notes, and are not generally useful. The public finished essays are good enough for general reader ("publication quality"). Private draft is private because others are unlikely to benefit from reading it, unless they are trying to impersonate the writer and enter their private world (["What is it like to be Person X?"](https://en.wikipedia.org/wiki/What_Is_It_Like_to_Be_a_Bat%3F)). Published essays are public because others are likely to benefit from it without entering the outside. They are pallets of information, like encapsulated software objects. You do not need to know how they were made to use them well.

The public draft is an interesting intermediate case. Sometimes there are things that are not already in a good enough shape to benefit others, but not good enough to count as a finished essay. They are like as public alphas of games. You can already play with them and have some fun with it, though only in bits and pieces; level 3 is followed by level 6; one NPC has a full personality while the other is a cardboard cutout. Similarly, a public draft is something that looks like an essay, except with pieces of it missing, the other pieces in the wrong place, some sentences missing their clauses, and some paragraphs missing their conclusions.

----

