# /etc/nginx/servers.d/yuxi.ml.conf
server {
  listen 443 ssl http2;
  listen [::]:443 ssl http2;
  server_name yuxi.ml;
  include /etc/nginx/snippets/ssl-yuxi.ml.conf;
  include /etc/nginx/snippets/acme-challenge.conf;

  root /var/www/yuxi.ml;
  index index.html;

  # external redirects
  if ($yuxi_redirect) { return 308 $yuxi_redirect; }

  # vanity: add trailing slash for single-segment paths
  if ($is_vanity$single_seg_noslash = 11) { return 308 $request_uri/; }

  # vanity: internal rewrite to deep folder
  if ($is_vanity) { rewrite ^/[^/]+(?:/(.*))?$ $vanity_target/$1 last; }

  location / { try_files $uri $uri/ =404; }
}
