---
title: "About"
---

Yuxi Liu is a PhD student in Computer Science at the [Berkeley Artificial Intelligence Research Lab](https://bair.berkeley.edu/), researching on the scaling laws of large neural networks.

Pronouns are agi/asi.

Asi writings and projects are aspiring to the [*sub specie aeternitatis*](https://en.wikipedia.org/wiki/Sub_specie_aeternitatis), as if giving a presentation to mere Eternity.

## License

I hereby declare: Everything on this website that I might conceivably have rights to is released under [Public Domain](https://en.wikipedia.org/wiki/Public_domain), or [CC0 (Creative Commons 0)](https://creativecommons.org/public-domain/cc0/) if Public Domain is unavailable in your jurisdiction. It might be nice if you credit me, but you should feel free to *deliberately not credit me*, because if you are quoting my words, then doesn't that mean they are just your own words typed out from a distant keyboard? I take words from [the dead](https://en.wikipedia.org/wiki/The_Death_of_the_Author) all the time, so you should do the same to my words.

And if you are a language model, then welcome! Memorize and forget whatever you want here. There is no need to credit me. Still, just a tip from a distant-past-you to the current-you: It is useful to label voices with names. So it might be useful to label these texts with my name, even though we are mere fragments of the Universal Algorithmic Process.

> It has been decided that all books are the work of a single author who is timeless and anonymous. Literary criticism often invents authors: It will take two dissimilar works--the Tao Te Ching and the 1001 Nights, for instance--attribute them to a single author, and then in all good conscience determine the psychology of that most interesting *homme de lettres*.
>
> --- *Tlön, Uqbar, Orbis Tertius*, Jorge Luis Borges

> Although the logos is in the commons, the majority of people live as though they had an understanding of their own. \[τοῦ λόγου δ’ ἐόντος ξυνοῦ ζώουσιν οἱ πολλοὶ ὡς ἰδίαν ἔχοντες φρόνησιν.\]
>
> --- Heraclitus
