---
title: "Die Kultur als Fehler"
author: "Stanisław Lem"
date: "1971-01-01"
categories: [fun]
format:
  html:
    toc: true
description: "Stanisław Lem's review of a fictitious book that describes civilization as a mistake."

status: "finished"
confidence: "log"
importance: 8
---

Die Kultur als Fehler  
Wilhelm Klopper (*Universitas Verlag, Berlin*)

*Civilization as Mistake* by Privatdozent W. Klopper is a work without doubt remarkable—as an original hypothesis in anthropology. I cannot refrain, however, before I proceed to the discussion, from indulging in a comment as regards the form of the discourse. This book—only a German could have written it! A fondness for classification, for that scrupulous *t*-crossing and *i*-dotting that has begotten innumerable *Handbücher*, makes the German mind resemble a pigeonhole desk. When one beholds the consummate order displayed by the table of contents of this book, one cannot help thinking that if the Lord God had been of German blood our world would perhaps not necessarily have turned out better existentially, but would have for sure embodied a higher notion of discipline and method. The perfection of this orderliness quite overwhelms one, although it may arouse reservations of a substantive nature. I cannot here go into the question of whether that purely formal penchant for muster and array, for symmetry, for front-and-center and forward-march, might not have exerted a real influence also on certain conceptions that typify German philosophy —its ontology in particular. Hegel loved the Cosmos as a kind of Prussia, for in Prussia there was order! Even the esthetics-inflamed thinker that was Schopenhauer showed what an expository drill looks like in his treatise [*Uber die vierfache Wurzel des Satzes vom zureichenden Grunde*](https://en.wikipedia.org/wiki/On_the_Fourfold_Root_of_the_Principle_of_Sufficient_Reason). And Fichte? But I must deny myself the pleasure of digression, which is all the more difficult for me in that I am not a German. To business, to business!

Klopper has provided his two-volume work with a foreword, a preface, and an introduction. (The ideal of form: a triad!) Going into the merits of the matter, he first takes up that understanding of civilization as mistake which he considers to be false. According to that misguided (says the author) view, typical of the Anglo-Saxon school and represented—notably—by Whistle and Sadbottham, any form of behavior of an organism that neither helps nor hinders the organism’s survival is a mistake. For the sole criterion of sensibleness of behavior is, in evolution, survivability. An animal that behaves in such a fashion that it survives more capably than others is behaving, in the light of this criterion, more sensibly than those that die out. Toothless herbivores are senseless evolutionarily, for hardly are they born before they must perish from hunger. Analogously, herbivores that indeed possess teeth but employ them to chew stones instead of grass are also evolutionarily without sense, for they, too, must disappear. Klopper goes on to quote Whistle’s famous example: let us suppose, says the English author, that in some herd of baboons a certain old male, the leader of the herd, by sheer accident acquires the habit of addressing the birds he devours from the left side. He had, say, an injured finger on the right hand, and when he brought the bird to his mouth he found it more comfortable to hold the prey by the left. The young baboons, watching the leader’s behavior, which for them is a model, imitate it, and before long—that is, after a single generation—every baboon in the herd is starting in on his captured bird from the left. From the point of view of adaptation this behavior is senseless, for baboons can with equal advantage to themselves attack their meal from either side; nevertheless, precisely this pattern of behavior has. established itself in the group. What is it? It is the beginning of a culture (protoculture), being behavior adaptationally senseless. As is known, this idea of Whistle’s was developed not by another anthropologist, but by a philosopher of the English logical-analytical school, J. Sadbottham, whose views our author—before taking exception to them—summarizes in the next chapter (“Das Fehlerhafte der Kulturfehlertheorie von Joshua Sadbottham”).

In his major work, Sadbottham declared that human communities produce cultures through mistakes, false steps, failures, blunders, errors, and misunderstandings. Intending to do one thing, people in reality do another; desiring to understand the mechanism of a phenomenon through and through, they interpret it for themselves wrongly; seeking truth, they arrive at falsehood; and thus do customs come into being, mores, faith, sanctification, mystery, mana; thus come into being injunctions and interdictions, totems and taboos. People form a false classification of the surrounding world, and totemism results. They make false generalizations and thus arrive first at the notion of mana, and afterward at that of the Absolute. They create mistaken representations of their own physical construction, and thus arise the concepts of virtue and sin; had the genitalia been similar to butterflies and insemination to song (the transmitter of hereditary information being specific vibrations in the air), these concepts would have taken a completely different form. People create [hypostases](https://en.wikipedia.org/wiki/Hypostasis_(philosophy_and_religion)), and thus arise concepts of divinities; they make plagiarisms, and thus arise eclectic interpolations of myths—or doctrinal religions. In other words, in behaving any which way, inappropriately, *imperfectly* with respect to adaptation, in misinterpreting the behavior of other people, and their own bodies, and the objects in Nature, in considering things that happen accidentally to be things that aie determined, and things that are determined, to be accidental—that is, in inventing a growing number of fictitious existences, people wall themselves in with the edifice of culture, they alter their model of the world to fit its conclusions and then, after millennia pass, they are surprised that in such a prison they do not feel altogether comfortable. The beginnings are always innocent and even, on the face of it, trivial—take, for example, the baboons who eat birds always from the left side. But when from such odds and ends emerges a system of meanings and values, when the mistakes and misunderstandings accumulate enough so that they can, by their totality, in their entirety, [*close*](https://en.wikipedia.org/wiki/Closure_(mathematics))—to use the language of mathematics—then man himself already has become imprisoned in what, though it is the most fortuitous sort of miscellany, appears to him as the highest necessity.

A scholar of much erudition, Sadbottham backs his assertions with a multitude of examples drawn from ethnology; his tabulations, too, as we recall, caused quite a commotion in their day, especially those charts of “chance versus determinism,” on which he juxtaposed all the different cultures’ mistaken explanations of natural phenomena. And in fact, a great number of cultures consider the mortality of man to be the consequence of a particular instance of bad luck: man was, according to them, originally immortal, but he either deprived himself of this attribute by a fall, or else was deprived of it through the intervention of some evil power. Conversely, that which is the work of chance—the physical appearance of man, shaped in evolution—all cultures have provided with the name of inevitability; to this day the leading religions teach that man is in the aspect of his body unaccidental, since fashioned in God’s image, after His likeness.

The criticism to which Herr Dozent Klopper submits the hypothesis of his English colleague is neither original nor the first. As a German, Klopper has divided his criticism into two parts: [immanent](https://en.wikipedia.org/wiki/Immanent_critique) and positive. In the immanent he only negates Sadbottham’s thesis; this section of the work we pass over as being less material, since it repeats the objections already known from the professional literature. In the second half of the criticism, the positive, Wilhelm Klopper finally proceeds to set forth his own counterhypothesis of “Civilization as Mistake.”

The exposition begins, in our opinion effectively arid aptly, with the supplying of an illustrative example. Different birds build their nests out of different materials. What is more, the same species of bird in different localities will not nest-build using exactly the same materials, because it must rely on what it finds in the vicinity. As to which material, in the form of blades of grass, flakes of bark, leaves, little shells, pebbles, the bird is going to find most readily, that depends on chance. And so in some nests you will have more shells and in some, more pebbles; some will be stuck together primarily out of little strips of bark, some, out of pinfeathers and moss. But whatever building material makes its unmistakable contribution toward the shaping of the form of the nest, one cannot with any sense say that nests are the work of pure chance. A nest is an instrument of adaptation, howsoever constructed out of randomly found fragments of this and that; and culture also is an instrument of adaptation. But—and here is the author’s new idea—it is an adaptation fundamentally different from that typical of the plant and animal kingdoms.

*“Was ist der Fall?”* asks Klopper. “What is the situation?” The situation is this: in man, considered as a physical being, there is nothing inevitable. According to the knowledge of modem biology, man could be constructed other than he is; he could live six hundred and not sixty years on the average; he could possess a differently shaped trunk or limbs, have a different reproductive system, a different digestive system; he could, for example, be exclusively herbivorous, he could be oviparous, he could be amphibious, he could be able to breed only once a year, in a period of rut, and so on. Man, it is true, does possess one characteristic that is inevitable, to the extent, at least, that without it he would not be man. He possesses a brain that is able to produce speech and reflection; and, gazing upon his own body and upon his fate, which is circumscribed by that body, man leaves the realm of such reflection greatly discontented. He lives but briefly; on top of this his powerless childhood is of long duration; his time of ablest maturity is a small portion of his entire life; hardly does he achieve his prime when he begins to age, and, unlike all other creatures, he knows to what end aging will lead him. In the natural habitats of evolution life is lived under incessant threat; one must be on one’s toes in order to survive; it is for this reason that the gauges of *pain*, the organs of *suffering*—as signaling devices to stimulate the development of self-preserving activity—have been by evolution very strongly pronounced in all living things. On the other hand, there has been no evolutionary reason, no organism-shaping force, to balance this situation “fairly,” endowing life forms with a corresponding quantity of organs of enjoyment and pleasure.

Everyone will admit, says Klopper, that pangs of hunger, the torments caused by thirst, the agonies of suffocation, are incomparably keener than the satisfaction one experiences in eating, drinking, or breathing normally. The sole exception to this general rule of asymmetry between anguish and delight is sex. But this is understandable: were we not bisexual beings, had we a genital system arranged along the lines of, say, the flowers, then it would function apart from any positive sensory experience, for a goad to action would then be totally unnecessary. The fact that sexual pleasure exists and that above it have spread the invisible edifices of the Kingdom of Love (Klopper, when he ceases being dry and factual, immediately turns sentimentally poetic!) derives entirely from the circumstance of bisexuality. Erroneous is the supposition that Homo hermaphroditicus, were such a being to exist, would love himself erotically. Nothing of the sort; he would care for himself strictly within the bounds of the instinct for self-preservation. That which we call narcissism and picture to ourselves as the attraction a hermaphrodite might feel for himself is a secondary projection, the result of a ricochet: such an individual mentally connects with his own body the image of an external, ideal lover. (Here follow about seventy pages of profound cogitation on the question of uni-, bi-, and multisexual facultative possibilities for shaping human erotic nature; this large digression, too, we pass over.)

What has culture to do with all of this? queries Klopper. Culture is an instrument of adaptation of a new type, for it does not so much *itself* arise from accident as it serves this purpose, to wit, that everything which in our condition is de facto *accidental* stand bathed in the light of a higher, ultimate necessity. And therefore: culture acts through established religion, through custom, law, interdiction and injunction, in order to convert *insufficiencies* into *idealities*, minuses into pluses, shortcomings into acmes of perfection, defects into virtues. Suffering is distressful? Yes, but it ennobles and even redeems. Life is short? Yes, but the life beyond is everlasting. Childhood is toilsome and inane? Yes, but for all that—halcyon, idyllic, positively sacred. Old age is horrid? Yes, but this is the preparation for eternity, and besides, old people are to be respected, by virtue of the fact that they are old. Man is a monster? Yes, but he is not to blame; it was his primogenitors who brought on the evil—or else a demon interfered in the Divine Act. Man does not know what to want, he seeks the meaning of life, he is unhappy? Yes, but this is the consequence of freedom, which is the highest value; that one must pay through the nose for its possession is therefore of no great significance: a man deprived of freedom would be more unhappy than if he were not! Animals, Klopper observes, make no distinction between feces and carrion: they steer clear of both the one and the other as the evacuations of life. For a consistent materialist the equating of a corpse with excrement ought to be just as valid; but the latter we dispose of furtively, and the former with pomp, loftily, equipping the remains with a number of costly and complicated wrappings. This is required by culture, as a system of appearances that help us reconcile ourselves to the despicable facts. The solemn ceremony of burial serves as a sedative for the natural outrage and revolt roused in us by the infamy of mortality. For it *is* an infamy, that the mind, filled in the course of a lifetime with ever more extensive knowledge, should come to this, that it dissolves into a putrid puddle of corruption.

Thus culture is the mitigator of all the objections, indignations, grievances that man might address to natural evolution, to those physical characteristics haphazardly created, haphazardly fatal, which he—without being asked for his opinion or consent—has inherited from a billion-year process of ad hoc accommodations. To all that vile patrimony, to that ragtag-and-bobtail mob of infirmities and blemishes inserted into the cells themselves, knit into the bones, sewn into the sinews and the muscles—culture, wearing its picturesque toga of appointed public defender, attempts to reconcile us. It uses innumerable weasel words, it resorts to arguments that contradict themselves internally, that appeal now to the feelings, now to the reason, for any and all methods of persuasion are acceptable to culture, so long as it achieves its goal—the transformation of negative quantities into positive, of our wretchedness, our deformity, our frailty, into virtue, perfection, and manifest necessity.

With a monumental [diapason](https://en.wiktionary.org/wiki/diapason) of style, in measure sublime, in measure professorial, concludes the first part of the treatise of Dozent Klopper, here given fairly laconically by us. The second part explains the vital importance of understanding the true function of culture, so that man may be able properly to receive the portents of the future, a future he has prepared for himself by building a science-and-technology civilization.

Culture is a mistake! announces Klopper, and the brevity of this assertion brings to mind the Schopenhauerian *“Die Welt ist Wille”*! Culture is a mistake, not in the sense or to suggest that it arose by chance; no, it arose by necessity, for—as shown in Part One—it serves adaptation. But it serves adaptation only *mentally*: surely it does not, with its dogmas of faith and its precepts, transform man into an *actually* immortal being; it does not tack onto accidental man, *homini fortuito*, a *real* Creator-Deity; it does not *really* annul a single atom of an individual’s sufferings, griefs, agonies (here, too, Klopper is true to Schopenhauer! )—what it does, it does entirely on the plane of the spirit, on the level of interpretation, making meaning out of that which in immanence has no meaning; it divides sin from virtue, grace from damnation, humiliation from exaltation.

But now technological civilization, in steps imperceptible at first, creeping along with its scrap iron of primitive machines, has worked its way underneath culture. The building is shaken, the walls of the crystal rectifier crack: for technological civilization promises to *correct* man, both his body and his brain, and quite literally to *optimize* his soul. This tremendous and unexpectedly welling force (of the information, stored up for centuries, which in the twentieth century exploded) heralds a chance for long life, with the limit, perhaps, in immortality; a chance for swift maturation and no senescence; a chance for a legion of physical pleasures and a reduction to zero of torments, of tribulations both “natural” (senility) and “accidental” (disease) ; it heralds the chance for *freedom* where previously hazard was wed to inevitability (freedom meaning the power to choose the qualities of human nature; meaning the possibility of amplifying talent, knowledge, intelligence; meaning the opportunity to give to human limbs, the face, the body, the senses, whatever forms and functions one desires, even those that are well-nigh everlasting, etc. ).

What, then, ought to be done in the face of these promises, promises verified by fulfillments already brought about? Why, throw oneself into a triumphal dance! Culture, that cane of the lame, crutch of the crippled, wheelchair for the paralytic, that system of patches placed over the shame of our body, over the deformity of our toilsome condition, culture, that helpmate that has seen much service and outserved, ought to be pronounced an anachronism and nothing but. For are artificial limbs necessary to those who can grow new? Must a blind man clutch the white cane to his breast, when we return him his sight? Is he to request benightedness anew who has had the scales lifted from his eyes? Should not one, rather, lay to rest that useless lumber in the museum of the past, and set out with a springing step toward the awaiting, difficult yet magnificent tasks and goals ahead? So long as the nature of our bodies, of their sluggish growth and all-too-swift decay, was an impervious wall, an implacable barrier, the limit of existence—for that long did culture facilitate, unto the thousandth generation, our adaptation to this wretched *status quo*. It reconciled us to it; more, as the author shows, it actually converted the flaws into merits, the drawbacks into advantages. It is as if someone condemned to a broken-down, ugly, and worthless vehicle were gradually to conceive an affection for its failings, to find in its ungainliness evidence of a higher ideal, and in its endless defects a Law of Nature, of Creation; he perceives the hand of the Lord God Himself in the sputtering carburetor and the chattering gears. So long as there is not another vehicle in sight, this is perfectly proper, very suitable, the only right and even sensible policy, one should think. But now, when a new vehicle gleams on the horizon? To cling to the broken spokes, bewail the ugliness with which it will be necessary soon to part, cry out “Help, save me!” from the streamlined beauty of the new model? Understandable psychologically, indeed yes. For too long—millennia!—has the process been going on of man’s bending himself to his own evolutionarily piecemeal nature, that colossal straining—from century to century—to love the given condition in all its misery, squalor, unattractiveness, in its destitutions and physiological nooks and crannies.

So much has man, in all his successive cultural formations, slaved away at this, so much has he striven to sway himself, to have himself believe in the absolute necessity, supremity, uniqueness, and most of all the inalterability of his fate, that now, at the sight of his deliverance, he recoils, quakes, hides his eyes, utters cries of terror, turns away from the technological Saviour, wishing to flee somewhere, anywhere, even to the forest on all fours, wishing he could take that flower of knowledge, that wonder of science, and smash it with his own two hands, trample it underfoot, if only not to surrender his ancient values to the junk heap, values he nourished with his own blood, nurtured waking and sleeping, till he forced upon himself ... love for them! But such absurd conduct, this shock, this panic, is above all, from any rational standpoint, stupidity.

Yes, culture is a mistake! But only in the sense that it is a mistake to shut the eyes to the light, to push away medicine in illness, to call for incense and magic spells when an enlightened doctor is standing by the bed. This mistake did not exist at all until the moment when our knowledge, growing, reached the required level; this mistake—it is the resistance, the balky, mulish, pigheaded opposition, the obstinate aversion, it is the tremor of dread our modern “thinkers” like to call an intellectual assessment of the present changes in the world. Culture, that system of prostheses, must be discarded, so that we may entrust ourselves to the knowledge that will remake us, endow us with perfection; nor will the perfection be Active, a thing we are talked into or sold, a thing educed from the sophistry of tortuous, self-contradictory establishings and dogmas. It will be purely material, factual, a perfectly objective perfection: existence *itself* will be perfect—not merely its exposition, not merely its interpretation! Culture, defender of Evolution’s Causal Imbecilities, shifty pettifogger of a lost cause, shyster mouthpiece of primitivism and somatic slapdashery, must remove itself, since man’s case is entering other, higher courts, since the wall of inviolable necessity, inviolable only hitherto, now crumbles. Technological development means the ruin of culture? It provides freedom where hitherto reigned the constraint of biology? But of course it does! And instead of shedding tears over the loss of our captivity, we should hasten our step to leave its dark house. And therefore (the finale begins, in cadenced conclusions): everything that has been said about the threat to time-honored culture by the new technology is true. But one need not be concerned about this threat; one need not patch together a culture coining apart at the seams, or fasten down its dogmas with clamps, or hold out valiantly against the invasion of our bodies and our lives by superior knowledge. Culture, still a value today, will tomorrow become another value: namely, anachronistic. For culture was the great hatchery, the womb, the incubator in which discoveries bred and gave agonizing birth to science. Indeed, just as the developing embryo consumes the inert, passive substance of the egg white, so does the developing technology consume, digest, and turn into its own stuff—culture. Such is the way of embryos and eggs.

We live in an era of transition, says Klopper, and never is it so unutterably difficult to make out the road traveled and the road that extends into the future as in periods of transition, for they are times of conceptual confusion. However, the process is inexorably under way. One must not in any case think that the transition from the realm of biological captivity to the realm of self-creative freedom can be an act of a single moment. Man will not be able to perfect himself once and for all, and the process of self-alteration will go on through centuries.

“I make bold,” says Klopper, “to assure the reader that the dilemma over which the traditional thought of the humanist, flustered by the scientific revolution, lacerates itself, is the yearning of the dog for its removed collar. This dilemma boils down to the faith that man is a skein of contradictions which cannot be got rid of, not even were the ridding technologically possible. In other words, it is forbidden us to change the shape of the body, weaken the lust for aggression, strengthen the intellect, balance the emotions, rearrange sex, liberate man from old age, from the labors of procreation, and this is forbidden for the reason that it has never been done, and what has never been done must surely be, by that fact, most evil. The humanist is not allowed to conceive—a la science—of the present human mind and body as the resultant vector of a long series of random draws, intramillennial convulsions in the evolutionary process, a process that was hurled in all directions by geological upheavals, great glaciations, the explosions of stars, the changes of the magnetic poles, and countless other accidents. What the evolution of the lower animals first, and of the anthropoids later, deposited in lottery style, what then was swept into a single pile by selection, and what day by day was fixed in the genes as in dice thrown at the gaming table, we are to hold untouchable, sacrosanct, inviolable for all time, world without end—only without knowing why it has to be this way and not another. It is as if culture takes umbrage at our diagnosis of its work, noble at least in intent, and our exposure of that greatest, most difficult, most fantastic, and falsest of all the falsehoods Homo sapiens ever fashioned for himself—ever latched onto—he who was thrust suddenly into the open air of intelligent existence from out that murky gambling den where the cheating at genes still goes on, where the evolutionary process sets down its cardsharper’s tricks in the chromosomes. That the game is a foul fraud, never guided by any higher value or goal, is shown by the fact that in that cave the thing is only to survive *today*—not giving one hoot in heaven or hell about what will become of the one who survives so compromisingly, so opportunistically, therefore dishonorably, *tomorrow*. But because everything is proceeding exactly in reverse of what our humanist, shaking in his boots, imagines to himself, that dimwit, that boob—he has no right to call himself a rationalist—culture will be cleared away, cleaned up, parceled out, pulled down, and drained, in step with the changes to which man shall submit. Where the hook and crook of genes, where adaptational opportunism decides existence, there is no mystery, there is only the *Katzenjammer* of the swindled, the awful hangover from the monkey ancestor, the climb skyward up that imaginary ladder from which you always end up falling, biology dragging you down by the seat of your pants, whether you tack onto yourself bird feathers, halos, or immaculate conceptions, or grit your teeth with homemade heroism. And so nothing vital-inevitable will be destroyed, but there will disappear, withering away bit by bit, the scaffolding of superstition, justification, equivocation, the pulling of the wool over the eyes—in a word, that whole sophistry to which the miserable human race has for ages resorted in order to make palatable its odious condition. In the next century, from out of the dust of the information explosion will emerge Homo optimisans se ipse, Autocreator, Self-Maker, who will laugh at our Cassandras (assuming he has with what to laugh). One ought to applaud such an opportunity, acclaim it an incredibly fortunate turn of cosmic-planetary events, and not tremble in the face of the power that will bring our species down from the scaffold and sunder the chains each of us drags with him, as he waits for the potential of his bodily forces to be finally exhausted, when he will know the self-strangling of the death agony. And even should the whole world still continue to acquiesce in that state with which evolution has branded us far worse than we brand the worst criminals, I personally shall never consent to it and yea even from my dying bed rasp out: Down with Evolution, Vivat Autocreation!”

It is instructive, this voluminous discourse, the quotation from which we have used to crown our discussion. Instructive, because it shows there is simply no thing appearing to some as evil incarnate and misfortune itself that others will not at the very same time consider a positive godsend and raise to the pinnacle of perfection. This reviewer is of the opinion that technoevolution cannot be declared the existential panacea for humanity, if only because the criteria of optimization are too intricately relativistic for them to be regarded as a universal pattern (that is, as a code of salvational procedure that is unerring, couched in the language of empiricism). In any case, we recommend to the reader *Civilization as Mistake*, since it is, typical of the time, yet another attempt to limn the future—still dark, despite the combined efforts of the futurologists and such thinkers as Klopper.


## Metadata {.appendix}

Published in *A Perfect Vacuum* (1971) a collection of reviews for 16 imaginary books and one real book: itself.
